package com.hcl.atf.taf.model.custom;

// Generated Aug 3, 2013 11:53:56 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestExecutionResult generated by hbm2java
 */
@Entity
@Table(name = "test_run_reports_device_list_view")
public class TestRunReportsDeviceList implements java.io.Serializable {

	private Integer testRunNo;
	private Integer testRunListId;
	private String productName;
	private String productVersionName;
	private String deviceId;
	private Integer deviceListId;
	private String devicePlatformName;
	private String devicePlatformVersion;
	private String deviceModel;
	private Date testRunTriggeredTime;
	private String testRunStatus;
	private String testRunFailureMessage;
	private Integer testSuiteId;
	private String testCaseName;
	private String testStep;
	private String testStepDescription;
	private String testStepInput;
	private String testStepExpectedOutput;
	private String testStepObservedOutput;
	private String testResultStatus;
	private String deviceTestRunResultStatus;
	private Integer testRunConfigurationChildId;
	private String testRunconfigurationName;
	private Date testRunStartTime;
	private Date testRunEndTime;
	private String testRunEvidenceStatus;
	private String hostName;
	private String hostIpAddress;
	private Integer hostId;
	private String hostPlatform;
	private String testEnvironmentName;

	public TestRunReportsDeviceList() {
		
	}

	public TestRunReportsDeviceList(Integer testRunNo, Integer testRunListId,
							String productName,
							String productVersionName,
							String deviceId,
							Integer deviceListId,
							String devicePlatformName,
							String devicePlatformVersion,
							String deviceModel,
							Date testRunTriggeredTime,
							String testRunStatus,
							String testRunFailureMessage,
							Integer testSuiteId,
							String testCaseName,
							String testStep,
							String testStepDescription,
							String testStepInput,
							String testStepExpectedOutput,
							String testStepObservedOutput,
							String testResultStatus,
							String deviceTestRunResultStatus,
							Integer testRunConfigurationChildId,
							String testRunconfigurationName,
							Date testRunStartTime,
							Date testRunEndTime,
							String hostName,
							String hostIpAddress,
							Integer hostId,
							String hostPlatform,
							String testRunEvidenceStatus) {
		this.testRunNo=testRunNo;
		this.testRunListId = testRunListId;
		this.productName = productName;
		this.productVersionName = productVersionName;
		this.deviceId = deviceId;
		this.deviceListId=deviceListId;
		this.devicePlatformName = devicePlatformName;
		this.devicePlatformVersion = devicePlatformVersion;
		this.deviceModel = deviceModel;
		this.testRunTriggeredTime = testRunTriggeredTime;
		this.testRunStatus = testRunStatus;
		this.testRunFailureMessage = testRunFailureMessage;
		this.testSuiteId=testSuiteId;
		this.testCaseName=testCaseName;
		this.testStep=testStep;
		this.testStepDescription=testStepDescription;
		this.testStepInput=testStepInput;
		this.testStepExpectedOutput=testStepExpectedOutput;
		this.testStepObservedOutput=testStepObservedOutput;
		this.testResultStatus=testResultStatus;
		this.deviceTestRunResultStatus=deviceTestRunResultStatus;
		this.testRunConfigurationChildId=testRunConfigurationChildId;
		this.testRunconfigurationName=testRunconfigurationName;
		this.testRunStartTime = testRunStartTime;
		this.testRunEndTime = testRunEndTime;
		this.testRunEvidenceStatus = testRunEvidenceStatus;
		this.hostId=hostId;
		this.hostName=hostName;
		this.hostIpAddress=hostIpAddress;
		this.hostPlatform=hostPlatform;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testRunListId", unique = true, nullable = false)
	public Integer getTestRunListId() {
		return this.testRunListId;
	}

	public void setTestRunListId(Integer testRunListId) {
		this.testRunListId = testRunListId;
	}

	@Column(name = "productName", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	@Column(name = "productVersionName", nullable = false, length = 50)
	public String getProductVersionName() {
		return productVersionName;
	}

	public void setProductVersionName(String productVersionName) {
		this.productVersionName = productVersionName;
	}
	@Column(name = "deviceId", nullable = false, length = 150)
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}
	@Column(name = "deviceListId", nullable = false, length = 11)
	public Integer getDeviceListId() {
		return deviceListId;
	}

	public void setDeviceListId(Integer deviceListId) {
		this.deviceListId = deviceListId;
	}
	@Column(name = "devicePlatformName", nullable = false, length = 50)
	public String getDevicePlatformName() {
		return devicePlatformName;
	}

	public void setDevicePlatformName(String devicePlatformName) {
		this.devicePlatformName = devicePlatformName;
	}
	@Column(name = "devicePlatformVersion", nullable = false, length = 50)
	public String getDevicePlatformVersion() {
		return devicePlatformVersion;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}
	
	@Column(name = "deviceModel", nullable = false, length = 100)
	public String getDeviceModel() {
		return deviceModel;
	}

	public void setDevicePlatformVersion(String devicePlatformVersion) {
		this.devicePlatformVersion = devicePlatformVersion;
	}

	
	@Column(name = "testRunTriggeredTime", nullable = false)
	public Date getTestRunTriggeredTime() {
		return testRunTriggeredTime;
	}

	public void setTestRunTriggeredTime(Date testRunTriggeredTime) {
		this.testRunTriggeredTime = testRunTriggeredTime;
	}
	@Column(name = "testRunStartTime", nullable = false)
	public Date getTestRunStartTime() {
		return testRunStartTime;
	}

	public void setTestRunStartTime(Date testRunStartTime) {
		this.testRunStartTime = testRunStartTime;
	}
	@Column(name = "testRunEndTime", nullable = false)
	public Date getTestRunEndTime() {
		return testRunEndTime;
	}

	public void setTestRunEndTime(Date testRunEndTime) {
		this.testRunEndTime = testRunEndTime;
	}
	@Column(name = "testRunStatus", nullable = false, length = 10)
	public String getTestRunStatus() {
		return testRunStatus;
	}

	public void setTestRunStatus(String testRunStatus) {
		this.testRunStatus = testRunStatus;
	}
	@Column(name = "testRunFailureMessage")
	public String getTestRunFailureMessage() {
		return testRunFailureMessage;
	}

	public void setTestRunFailureMessage(String testRunFailureMessage) {
		this.testRunFailureMessage = testRunFailureMessage;
	}
	@Column(name = "DeviceTestRunResultStatus", nullable = false, length = 6)
	public String getDeviceTestRunResultStatus() {
		return deviceTestRunResultStatus;
	}

	public void setDeviceTestRunResultStatus(String deviceTestRunResultStatus) {
		this.deviceTestRunResultStatus = deviceTestRunResultStatus;
	}
	@Column(name = "testRunNo", nullable = false, length = 11)
	public Integer getTestRunNo() {
		return testRunNo;
	}

	public void setTestRunNo(Integer testRunNo) {
		this.testRunNo = testRunNo;
	}
	@Column(name = "testSuiteId", nullable = false, length = 11)
	public Integer getTestSuiteId() {
		return testSuiteId;
	}

	public void setTestSuiteId(Integer testSuiteId) {
		this.testSuiteId = testSuiteId;
	}
	@Column(name = "testCaseName", nullable = false, length = 100)
	public String getTestCaseName() {
		return testCaseName;
	}

	public void setTestCaseName(String testCaseName) {
		this.testCaseName = testCaseName;
	}
	@Column(name = "testStep", nullable = false, length = 100)
	public String getTestStep() {
		return testStep;
	}

	public void setTestStep(String testStep) {
		this.testStep = testStep;
	}
	@Column(name = "testStepDescription", nullable = false, length = 200)
	public String getTestStepDescription() {
		return testStepDescription;
	}

	public void setTestStepDescription(String testStepDescription) {
		this.testStepDescription = testStepDescription;
	}
	@Column(name = "testStepInput", nullable = false, length = 100)
	public String getTestStepInput() {
		return testStepInput;
	}

	public void setTestStepInput(String testStepInput) {
		this.testStepInput = testStepInput;
	}
	@Column(name = "testStepExpectedOutput", nullable = false, length = 100)
	public String getTestStepExpectedOutput() {
		return testStepExpectedOutput;
	}

	public void setTestStepExpectedOutput(String testStepExpectedOutput) {
		this.testStepExpectedOutput = testStepExpectedOutput;
	}
	@Column(name = "testStepObservedOutput", nullable = false, length = 100)
	public String getTestStepObservedOutput() {
		return testStepObservedOutput;
	}

	public void setTestStepObservedOutput(String testStepObservedOutput) {
		this.testStepObservedOutput = testStepObservedOutput;
	}
	@Column(name = "testResultStatus", nullable = false, length = 100)
	public String getTestResultStatus() {
		return testResultStatus;
	}

	public void setTestResultStatus(String testResultStatus) {
		this.testResultStatus = testResultStatus;
	}
	@Column(name = "testRunConfigurationChildId", nullable = false, length = 11)
	public Integer getTestRunConfigurationChildId() {
		return testRunConfigurationChildId;
	}

	public void setTestRunConfigurationChildId(Integer testRunConfigurationChildId) {
		this.testRunConfigurationChildId = testRunConfigurationChildId;
	}
	@Column(name = "testRunconfigurationName", nullable = false, length = 80)
	public String getTestRunconfigurationName() {
		return testRunconfigurationName;
	}

	public void setTestRunconfigurationName(String testRunconfigurationName) {
		this.testRunconfigurationName = testRunconfigurationName;
	}
	@Column(name = "testRunEvidenceStatus")
	public String getTestRunEvidenceStatus() {
		return testRunEvidenceStatus;
	}
	public void setTestRunEvidenceStatus(String testRunEvidenceStatus) {
		this.testRunEvidenceStatus = testRunEvidenceStatus;
	}
	@Column(name = "hostName")
	public String getHostName() {
		return hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}
	@Column(name = "hostIpAddress")
	public String getHostIpAddress() {
		return hostIpAddress;
	}

	public void setHostIpAddress(String hostIpAddress) {
		this.hostIpAddress = hostIpAddress;
	}
	@Column(name = "hostId")
	public Integer getHostId() {
		return hostId;
	}

	public void setHostId(Integer hostId) {
		this.hostId = hostId;
	}
	@Column(name = "hostPlatform")
	public String getHostPlatform() {
		return hostPlatform;
	}
	@Column(name = "testEnvironmentName")
	public void setHostPlatform(String hostPlatform) {
		this.hostPlatform = hostPlatform;
	}
	public String getTestEnvironmentName() {
		return testEnvironmentName;
	}
	public void setTestEnvironmentName(String testEnvironmentName) {
		this.testEnvironmentName = testEnvironmentName;
	}

}
