package com.hcl.atf.taf.model.custom;

// Generated Aug 3, 2013 11:53:56 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestExecutionResult generated by hbm2java
 */
@Entity
@Table(name = "testrunreports_testcases_devicedetails_view")
public class TestRunReportsDeviceCaseList implements java.io.Serializable {

	private Integer testRunNo;
	private Integer testRunListId;
	private String productName;
	private String productVersionName;
	private String deviceId;
	private String devicePlatformName;
	private String devicePlatformVersion;
	private Integer testRunConfigurationChildId;
	private String testRunconfigurationName;
	private Date testRunTriggeredTime;
	private String testRunStatus;
	private String testRunFailureMessage;
	private Integer testSuiteId;
	private String testSuiteName;
	private Integer testCaseId;
	private String testCaseName;
	private String testCaseDescription;
	private String testCaseResult;
	private Date testCaseStartTime;
	private Date testCaseEndTime;
	private Integer hostId;
	private String hostName;
	private String hostIpAddress;
	private String hostPlatform;
	
	
	public TestRunReportsDeviceCaseList() {
		
	}

	public TestRunReportsDeviceCaseList(Integer testRunNo, Integer testRunListId,
							String productName,
							String productVersionName,
							String deviceId,
							String devicePlatformName,
							String devicePlatformVersion,
							Integer testRunConfigurationChildId,
							String testRunconfigurationName,
							Date testRunTriggeredTime,
							String testRunStatus,
							String testRunFailureMessage,
							Integer testSuiteId,
							String testSuiteName,
							Integer testCaseId,
							String testCaseName,
							String testCaseDescription,
							String testCaseResult,
							Date testCaseStartTime,
							Date testCaseEndTime,
							Integer hostId,
							String hostName,
							String hostIpAddress,
							String hostPlatform) {
		this.testRunNo=testRunNo;
		this.testRunListId = testRunListId;
		this.productName = productName;
		this.productVersionName = productVersionName;
		this.deviceId = deviceId;
		this.devicePlatformName = devicePlatformName;
		this.devicePlatformVersion = devicePlatformVersion;
		this.testRunConfigurationChildId=testRunConfigurationChildId;
		this.testRunconfigurationName=testRunconfigurationName;
		this.testRunTriggeredTime = testRunTriggeredTime;
		this.testRunStatus = testRunStatus;
		this.testRunFailureMessage = testRunFailureMessage;
		this.testSuiteId=testSuiteId;
		this.testSuiteName=testSuiteName;
		this.testCaseId=testCaseId;
		this.testCaseName=testCaseName;
		this.testCaseDescription=testCaseDescription;
		this.testCaseResult=testCaseResult;
		this.testCaseStartTime=testCaseStartTime;
		this.testCaseEndTime=testCaseEndTime;
		this.hostId=hostId;
		this.hostName=hostName;
		this.hostIpAddress=hostIpAddress;
		this.hostPlatform=hostPlatform;
	}
	

	
	@Column(name = "testRunListId", unique = true, nullable = false)
	public Integer getTestRunListId() {
		return this.testRunListId;
	}

	public void setTestRunListId(Integer testRunListId) {
		this.testRunListId = testRunListId;
	}

	@Column(name = "productName", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	@Column(name = "productVersionName", nullable = false, length = 50)
	public String getProductVersionName() {
		return productVersionName;
	}

	public void setProductVersionName(String productVersionName) {
		this.productVersionName = productVersionName;
	}
	@Column(name = "deviceId", nullable = false, length = 150)
	public String getDeviceId() {
		return deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}
	
	@Column(name = "devicePlatformName", nullable = false, length = 50)
	public String getDevicePlatformName() {
		return devicePlatformName;
	}

	public void setDevicePlatformName(String devicePlatformName) {
		this.devicePlatformName = devicePlatformName;
	}
	@Column(name = "devicePlatformVersion", nullable = false, length = 50)
	public String getDevicePlatformVersion() {
		return devicePlatformVersion;
	}

	public void setDevicePlatformVersion(String devicePlatformVersion) {
		this.devicePlatformVersion = devicePlatformVersion;
	}
	@Column(name = "testRunTriggeredTime", nullable = false)
	public Date getTestRunTriggeredTime() {
		return testRunTriggeredTime;
	}

	public void setTestRunTriggeredTime(Date testRunTriggeredTime) {
		this.testRunTriggeredTime = testRunTriggeredTime;
	}
	@Column(name = "testRunStatus", nullable = false, length = 10)
	public String getTestRunStatus() {
		return testRunStatus;
	}

	public void setTestRunStatus(String testRunStatus) {
		this.testRunStatus = testRunStatus;
	}
	@Column(name = "testRunFailureMessage", nullable = false, length = 100)
	public String getTestRunFailureMessage() {
		return testRunFailureMessage;
	}

	public void setTestRunFailureMessage(String testRunFailureMessage) {
		this.testRunFailureMessage = testRunFailureMessage;
	}
	
	@Column(name = "testRunNo", nullable = false, length = 11)
	public Integer getTestRunNo() {
		return testRunNo;
	}

	public void setTestRunNo(Integer testRunNo) {
		this.testRunNo = testRunNo;
	}
	@Column(name = "testSuiteId", nullable = false, length = 11)
	public Integer getTestSuiteId() {
		return testSuiteId;
	}

	public void setTestSuiteId(Integer testSuiteId) {
		this.testSuiteId = testSuiteId;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testCaseId", nullable = false, length = 11)
	public Integer getTestCaseId() {
		return testCaseId;
	}

	public void setTestCaseId(Integer testCaseId) {
		this.testCaseId = testCaseId;
	}
	
	@Column(name = "testCaseName", nullable = false, length = 100)
	public String getTestCaseName() {
		return testCaseName;
	}

	public void setTestCaseName(String testCaseName) {
		this.testCaseName = testCaseName;
	}
	
	@Column(name = "testRunConfigurationChildId", nullable = false, length = 11)
	public Integer getTestRunConfigurationChildId() {
		return testRunConfigurationChildId;
	}

	public void setTestRunConfigurationChildId(Integer testRunConfigurationChildId) {
		this.testRunConfigurationChildId = testRunConfigurationChildId;
	}
	@Column(name = "testRunconfigurationName", nullable = false, length = 80)
	public String getTestRunconfigurationName() {
		return testRunconfigurationName;
	}

	public void setTestRunconfigurationName(String testRunconfigurationName) {
		this.testRunconfigurationName = testRunconfigurationName;
	}
	@Column(name = "testSuiteName", nullable = false, length = 80)
	public String getTestSuiteName() {
		return testSuiteName;
	}

	public void setTestSuiteName(String testSuiteName) {
		this.testSuiteName = testSuiteName;
	}
	@Column(name = "testCaseResult", nullable = false, length = 10)
	public String getTestCaseResult() {
		return testCaseResult;
	}

	public void setTestCaseResult(String testCaseResult) {
		this.testCaseResult = testCaseResult;
	}
	@Column(name = "testCaseStartTime", nullable = false)
	public Date getTestCaseStartTime() {
		return testCaseStartTime;
	}

	public void setTestCaseStartTime(Date testCaseStartTime) {
		this.testCaseStartTime = testCaseStartTime;
	}
	@Column(name = "testCaseEndTime", nullable = false)
	public Date getTestCaseEndTime() {
		return testCaseEndTime;
	}

	public void setTestCaseEndTime(Date testCaseEndTime) {
		this.testCaseEndTime = testCaseEndTime;
	}
	@Column(name = "testCaseDescription", nullable = false, length = 20000)
	public String getTestCaseDescription() {
		return testCaseDescription;
	}

	public void setTestCaseDescription(String testCaseDescription) {
		this.testCaseDescription = testCaseDescription;
	}
	@Column(name = "hostId")
	public Integer getHostId() {
		return hostId;
	}

	public void setHostId(Integer hostId) {
		this.hostId = hostId;
	}
	@Column(name = "hostName")
	public String getHostName() {
		return hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}
	@Column(name = "hostIpAddress")
	public String getHostIpAddress() {
		return hostIpAddress;
	}

	public void setHostIpAddress(String hostIpAddress) {
		this.hostIpAddress = hostIpAddress;
	}
	@Column(name = "hostPlatform")
	public String getHostPlatform() {
		return hostPlatform;
	}

	public void setHostPlatform(String hostPlatform) {
		this.hostPlatform = hostPlatform;
	}

	

}
