package com.hcl.atf.taf.model.custom;

// Generated Aug 3, 2013 11:53:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestExecutionResult generated by hbm2java
 */
@Entity
@Table(name = "testrunreports_teststeps_devicedetails_view")
public class TestRunReportsDeviceCaseStepList implements java.io.Serializable {
	private Integer testrunno;
	private Integer testrunlistid;
	private Integer productid;
	private String productname;
	private Integer productversionlistid;
	private String productversionname;
	private String deviceid;
	private String deviceplatformname;
	private String deviceplatformversion;
	private String testenvironmentname;
	private Integer testrunconfigurationchildid;
	private String testrunconfigurationname;
	private Date testruntriggeredtime;
	private Integer testrunstatus;
	private Integer testsuiteid;
	private String testsuitename;
	private Integer testcaseid;
	private String testcasename;
	private Integer teststepid;
	private String teststepname;
	private String teststepdescription;
	private String teststepinput;
	private String teststepexpectedoutput;
	private String teststepobservedoutput;
	private String teststepresult;
	private String executionremarks;
	private String failurereason;
	private Date teststepstarttime;
	private Date teststependtime;
	private String screenshotpath;
	private String screenshotlabel;
	private Integer hostid;
	private String hostname;
	private String hostipaddress;
	private String hostplatform;
	private String totaltime;
	private String teststepcode;
	private Integer teststepexecutionid;
	private Integer environmentcombinationid;
	private Integer testjobid;

	public TestRunReportsDeviceCaseStepList() {

	}

	public TestRunReportsDeviceCaseStepList(Integer testStepExecutionId,
			Integer testRunNo, 
			Integer testRunListId,
			Integer productId,
			String productName,
			Integer productVersionListId,
			String productVersionName,
			String deviceId,
			String devicePlatformName,
			String devicePlatformVersion,
			String testEnvironmentName,
			Integer testRunConfigurationChildId,
			String testRunconfigurationName,
			Date testRunTriggeredTime,
			Integer testRunStatus,
			Integer testSuiteId,
			String testSuiteName,
			Integer testCaseId,
			String testCaseName,
			Integer testStepId,
			String testStepName,
			String testStepDescription,
			String testStepInput,
			String testStepExpectedOutput,
			String testStepObservedOutput,
			String testStepResult,
			String executionRemarks,
			String failureReason,
			Date testStepStartTime,
			Date testStepEndTime,
			String screenShotPath,
			String screenShotLabel,
			Integer hostId,
			String hostName,
			String hostIpAddress,
			String hostPlatform,
			String testStepCode,
			Integer environmentcombinationid,
			Integer testjobid
			) {
		this.teststepexecutionid= testStepExecutionId;
		this.testrunno=testRunNo;
		this.testrunlistid = testRunListId;
		this.productid = productId;
		this.productname = productName;
		this.productversionlistid=productVersionListId;
		this.productversionname = productVersionName;
		this.deviceid = deviceId;
		this.deviceplatformname = devicePlatformName;
		this.deviceplatformversion = devicePlatformVersion;
		this.testenvironmentname = testEnvironmentName;
		this.testrunconfigurationchildid=testRunConfigurationChildId;
		this.testrunconfigurationname = testRunconfigurationName;
		this.testruntriggeredtime = testRunTriggeredTime;
		this.testrunstatus = testRunStatus;
		this.testsuiteid=testSuiteId;
		this.testsuitename=testSuiteName;
		this.testcaseid=testCaseId;
		this.testcasename=testCaseName;
		this.teststepid=testStepId;
		this.teststepname=testStepName;
		this.teststepdescription=testStepDescription;
		this.teststepinput=testStepInput;
		this.teststepexpectedoutput=testStepExpectedOutput;
		this.teststepobservedoutput=testStepObservedOutput;
		this.teststepresult=testStepResult;
		this.executionremarks=executionRemarks;
		this.failurereason=failureReason;
		this.teststepstarttime=testStepStartTime;
		this.teststependtime=testStepEndTime;
		this.screenshotpath = screenShotPath;
		this.screenshotlabel = screenShotLabel;
		this.hostid=hostId;
		this.hostname=hostName;
		this.hostipaddress=hostIpAddress;
		this.hostplatform=hostPlatform;
		this.teststepcode=testStepCode;
		this.environmentcombinationid = environmentcombinationid;
		this.testjobid = testjobid;
	}

	@Column(name = "testRunNo", nullable = false, length = 11)
	public Integer getTestrunno() {
		return testrunno;
	}

	public void setTestrunno(Integer testrunno) {
		this.testrunno = testrunno;
	}

	@Column(name = "testRunListId", unique = true, nullable = false)
	public Integer getTestrunlistid() {
		return testrunlistid;
	}

	public void setTestrunlistid(Integer testrunlistid) {
		this.testrunlistid = testrunlistid;
	}

	@Column(name = "productId", nullable = false, length = 11)
	public Integer getProductid() {
		return productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "productName", nullable = false, length = 100)
	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "productVersionListId", nullable = false, length = 11)
	public Integer getProductversionlistid() {
		return productversionlistid;
	}

	public void setProductversionlistid(Integer productversionlistid) {
		this.productversionlistid = productversionlistid;
	}

	@Column(name = "productVersionName", nullable = false, length = 50)
	public String getProductversionname() {
		return productversionname;
	}

	public void setProductversionname(String productversionname) {
		this.productversionname = productversionname;
	}

	@Column(name = "deviceId", nullable = false, length = 150)
	public String getDeviceid() {
		return deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	@Column(name = "devicePlatformName", nullable = false, length = 50)
	public String getDeviceplatformname() {
		return deviceplatformname;
	}

	public void setDeviceplatformname(String deviceplatformname) {
		this.deviceplatformname = deviceplatformname;
	}

	@Column(name = "devicePlatformVersion", nullable = false, length = 50)
	public String getDeviceplatformversion() {
		return deviceplatformversion;
	}

	public void setDeviceplatformversion(String deviceplatformversion) {
		this.deviceplatformversion = deviceplatformversion;
	}

	@Column(name = "testEnvironmentName", length = 200)
	public String getTestenvironmentname() {
		return testenvironmentname;
	}

	public void setTestenvironmentname(String testenvironmentname) {
		this.testenvironmentname = testenvironmentname;
	}

	@Column(name = "testRunConfigurationChildId", nullable = false, length = 11)
	public Integer getTestrunconfigurationchildid() {
		return testrunconfigurationchildid;
	}

	public void setTestrunconfigurationchildid(Integer testrunconfigurationchildid) {
		this.testrunconfigurationchildid = testrunconfigurationchildid;
	}

	@Column(name = "testRunconfigurationName", nullable = false, length = 80)
	public String getTestrunconfigurationname() {
		return testrunconfigurationname;
	}

	public void setTestrunconfigurationname(String testrunconfigurationname) {
		this.testrunconfigurationname = testrunconfigurationname;
	}

	@Column(name = "testRunTriggeredTime", nullable = false)
	public Date getTestruntriggeredtime() {
		return testruntriggeredtime;
	}

	public void setTestruntriggeredtime(Date testruntriggeredtime) {
		this.testruntriggeredtime = testruntriggeredtime;
	}

	@Column(name = "testRunStatus", nullable = false, length = 10)
	public Integer getTestrunstatus() {
		return testrunstatus;
	}

	public void setTestrunstatus(Integer testrunstatus) {
		this.testrunstatus = testrunstatus;
	}

	@Column(name = "testSuiteId", nullable = false, length = 11)
	public Integer getTestsuiteid() {
		return testsuiteid;
	}

	public void setTestsuiteid(Integer testsuiteid) {
		this.testsuiteid = testsuiteid;
	}

	@Column(name = "testSuiteName", nullable = false, length = 80)
	public String getTestsuitename() {
		return testsuitename;
	}

	public void setTestsuitename(String testsuitename) {
		this.testsuitename = testsuitename;
	}

	@Column(name = "testCaseId", nullable = false, length = 11)
	public Integer getTestcaseid() {
		return testcaseid;
	}

	public void setTestcaseid(Integer testcaseid) {
		this.testcaseid = testcaseid;
	}

	@Column(name = "testCaseName", nullable = false, length = 100)
	public String getTestcasename() {
		return testcasename;
	}

	public void setTestcasename(String testcasename) {
		this.testcasename = testcasename;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testStepId", nullable = false, length = 11)
	public Integer getTeststepid() {
		return teststepid;
	}

	public void setTeststepid(Integer teststepid) {
		this.teststepid = teststepid;
	}
	
	@Column(name = "testStepName", nullable = false, length = 100)
	public String getTeststepname() {
		return teststepname;
	}

	public void setTeststepname(String teststepname) {
		this.teststepname = teststepname;
	}

	@Column(name = "testStepDescription", nullable = false, length = 200)
	public String getTeststepdescription() {
		return teststepdescription;
	}

	public void setTeststepdescription(String teststepdescription) {
		this.teststepdescription = teststepdescription;
	}

	@Column(name = "testStepInput", nullable = false, length = 100)
	public String getTeststepinput() {
		return teststepinput;
	}

	public void setTeststepinput(String teststepinput) {
		this.teststepinput = teststepinput;
	}

	@Column(name = "testStepExpectedOutput", nullable = false, length = 100)
	public String getTeststepexpectedoutput() {
		return teststepexpectedoutput;
	}

	public void setTeststepexpectedoutput(String teststepexpectedoutput) {
		this.teststepexpectedoutput = teststepexpectedoutput;
	}

	@Column(name = "testStepObservedOutput", nullable = false, length = 100)
	public String getTeststepobservedoutput() {
		return teststepobservedoutput;
	}

	public void setTeststepobservedoutput(String teststepobservedoutput) {
		this.teststepobservedoutput = teststepobservedoutput;
	}

	@Column(name = "testStepResult", nullable = false, length = 10) 
	public String getTeststepresult() {
		return teststepresult;
	}

	public void setTeststepresult(String teststepresult) {
		this.teststepresult = teststepresult;
	}

	@Column(name = "executionRemarks", nullable = false, length = 2000) 
	public String getExecutionremarks() {
		return executionremarks;
	}

	public void setExecutionremarks(String executionremarks) {
		this.executionremarks = executionremarks;
	}

	@Column(name = "failureReason", nullable = false, length = 2000) 	
	public String getFailurereason() {
		return failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "testStepStartTime", nullable = false)
	public Date getTeststepstarttime() {
		return teststepstarttime;
	}

	public void setTeststepstarttime(Date teststepstarttime) {
		this.teststepstarttime = teststepstarttime;
	}

	@Column(name = "testStepEndTime", nullable = false)
	public Date getTeststependtime() {
		return teststependtime;
	}

	public void setTeststependtime(Date teststependtime) {
		this.teststependtime = teststependtime;
	}

	@Column(name = "screenShotPath", nullable = false)
	public String getScreenshotpath() {
		return screenshotpath;
	}

	public void setScreenshotpath(String screenshotpath) {
		this.screenshotpath = screenshotpath;
	}

	@Column(name = "screenShotLabel")
	public String getScreenshotlabel() {
		return screenshotlabel;
	}

	public void setScreenshotlabel(String screenshotlabel) {
		this.screenshotlabel = screenshotlabel;
	}

	@Column(name = "hostId")
	public Integer getHostid() {
		return hostid;
	}

	public void setHostid(Integer hostid) {
		this.hostid = hostid;
	}

	@Column(name = "hostName")
	public String getHostname() {
		return hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	@Column(name = "hostIpAddress")
	public String getHostipaddress() {
		return hostipaddress;
	}

	public void setHostipaddress(String hostipaddress) {
		this.hostipaddress = hostipaddress;
	}

	@Column(name = "hostPlatform")
	public String getHostplatform() {
		return hostplatform;
	}

	public void setHostplatform(String hostplatform) {
		this.hostplatform = hostplatform;
	}
	
	@Column(name = "totalTime")
	public String getTotaltime() {
		return totaltime;
	}

	public void setTotaltime(String totaltime) {
		this.totaltime = totaltime;
	}

	
	public String getTeststepcode() {
		return teststepcode;
	}

	public void setTeststepcode(String teststepcode) {
		this.teststepcode = teststepcode;
	}

	@Column(name = "teststepexecutionid", nullable = false, length = 11)
	public Integer getTeststepexecutionid() {
		return teststepexecutionid;
	}

	public void setTeststepexecutionid(Integer teststepexecutionid) {
		this.teststepexecutionid = teststepexecutionid;
	}
	@Column(name = "environmentcombinationid", nullable = false, length = 11)
	public Integer getEnvironmentcombinationid() {
		return environmentcombinationid;
	}

	public void setEnvironmentcombinationid(Integer environmentcombinationid) {
		this.environmentcombinationid = environmentcombinationid;
	}
	@Column(name = "testjobid", nullable = false, length = 11)
	public Integer getTestjobid() {
		return testjobid;
	}

	public void setTestjobid(Integer testjobid) {
		this.testjobid = testjobid;
	}
	
	
	
}
