package com.hcl.atf.taf.model.custom;

// Generated Oct 9, 2013 12:43:19 PM by Hibernate Tools 3.2.4.GA

import com.hcl.atf.taf.model.TestRunList;

/**
 * TestRunListCustom generated by own
 */

public class TestRunListCustom implements java.io.Serializable {

	private TestRunList testRunList;
	private int executedTestStepsCounts=0;
	private int totalTestStepCount=0;
	private int averageTestExecutionTime=0;
	private int elapsedTestExecutionTime=0;
	private int remainingTestExecutionTime=0;
	
	public TestRunListCustom() {
	}

	public TestRunListCustom(TestRunList testRunList,
			int executedTestStepsCounts) {
		this.testRunList = testRunList;
		this.executedTestStepsCounts = executedTestStepsCounts;
	}

	
	public TestRunList getTestRunList() {
		return testRunList;
	}

	public void setTestRunList(TestRunList testRunList) {
		this.testRunList = testRunList;
	}

	public int getExecutedTestStepsCounts() {
		return executedTestStepsCounts;
	}

	public void setExecutedTestStepsCounts(int executedTestStepsCounts) {
		this.executedTestStepsCounts = executedTestStepsCounts;
	}
	public int getTotalTestStepCount() {
		return totalTestStepCount;
	}

	public void setTotalTestStepCount(int totalTestStepCount) {
		this.totalTestStepCount = totalTestStepCount;
	}

	public int getAverageTestExecutionTime() {
		return averageTestExecutionTime;
	}

	public void setAverageTestExecutionTime(int averageTestExecutionTime) {
		this.averageTestExecutionTime = averageTestExecutionTime;
	}

	public int getElapsedTestExecutionTime() {
		return elapsedTestExecutionTime;
	}

	public void setElapsedTestExecutionTime(int elapsedTestExecutionTime) {
		this.elapsedTestExecutionTime = elapsedTestExecutionTime;
	}

	public int getRemainingTestExecutionTime() {
		return remainingTestExecutionTime;
	}

	public void setRemainingTestExecutionTime(int remainingTestExecutionTime) {
		this.remainingTestExecutionTime = remainingTestExecutionTime;
	}


}
