package com.hcl.atf.taf.model.custom;

// Generated Aug 3, 2013 11:53:56 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestExecutionResult generated by hbm2java
 */
@Entity
@Table(name = "test_run_reports_list_view")
public class TestRunReportsList implements java.io.Serializable {

	private Integer testRunNo;
	private Integer testRunListId;
	private String productName;
	private String productVersionName;
	private Date testRunTriggeredTime;
	private String testRunResultStatus;
	private Integer testRunConfigurationChildId;
	private String testRunConfigurationName;

	public TestRunReportsList() {
		
	}

	public TestRunReportsList(Integer testRunNo,
							Integer testRunListId,
							String productName,
							String productVersionName,
							Date testRunTriggeredTime,
							String testRunResultStatus,
							Integer testRunConfigurationChildId,
							String testRunConfigurationName) {
		
		this.testRunNo=testRunNo;
		this.testRunListId=testRunListId;
		this.productName=productName;
		this.productVersionName=productVersionName;
		this.testRunTriggeredTime=testRunTriggeredTime;
		this.testRunResultStatus=testRunResultStatus;
		this.testRunConfigurationChildId=testRunConfigurationChildId;
		this.testRunConfigurationName=testRunConfigurationName;
	}
	

	
	@Column(name = "testRunNo",  nullable = false)
	public Integer getTestRunNo() {
		return this.testRunNo;
	}

	public void setTestRunNo(Integer testRunNo) {
		this.testRunNo = testRunNo;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testRunListId", unique = true, nullable = false)
	public Integer getTestRunListId() {
		return this.testRunListId;
	}

	public void setTestRunListId(Integer testRunListId) {
		this.testRunListId = testRunListId;
	}
	@Column(name = "productName", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}
	@Column(name = "productVersionName", nullable = false, length = 50)
	public String getProductVersionName() {
		return productVersionName;
	}

	public void setProductVersionName(String productVersionName) {
		this.productVersionName = productVersionName;
	}
	@Column(name = "testRunTriggeredTime")
	public Date getTestRunTriggeredTime() {
		return testRunTriggeredTime;
	}

	public void setTestRunTriggeredTime(Date testRunTriggeredTime) {
		this.testRunTriggeredTime = testRunTriggeredTime;
	}
	@Column(name = "testRunResultStatus", nullable = false, length = 6)
	public String getTestRunResultStatus() {
		return testRunResultStatus;
	}

	public void setTestRunResultStatus(String testRunResultStatus) {
		this.testRunResultStatus = testRunResultStatus;
	}
	@Column(name = "testRunConfigurationChildId", nullable = false, length=11)
	public Integer getTestRunConfigurationChildId() {
		return testRunConfigurationChildId;
	}

	public void setTestRunConfigurationChildId(Integer testRunConfigurationChildId) {
		this.testRunConfigurationChildId = testRunConfigurationChildId;
	}
	@Column(name = "testRunConfigurationName", nullable = false, length=100)
	public String getTestRunConfigurationName() {
		return testRunConfigurationName;
	}

	public void setTestRunConfigurationName(String testRunConfigurationName) {
		this.testRunConfigurationName = testRunConfigurationName;
	}

}
