package com.hcl.atf.taf.report.xml.beans;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestExecutionResult generated by hbm2java
 */

public class TestExecutionResultBean implements java.io.Serializable {

	private Integer testExecutionResultId;
	/*private TestRunListBean testRunList;
	private TestResultStatusMasterBean testResultStatusMaster;
	private TestCaseListBean testCaseList;
	private TestCaseStepsListBean testCaseStepsList;*/
	private TestSuiteListBean testSuiteList;
	private String testStep;
	private String testStepDescription;
	private String testStepInput;
	private String testStepExpectedOutput;
	private String testStepObservedOutput;
	private String testCase;
	private String testCaseDescription;
	private String screenShotPath;
	private String screenShotLabel;
	private Date startTime;
	private Date endTime;
	private String failureReason;
	private String executionRemarks;
	/*private Set<TestExecutionResultBugList> testExecutionResultBugLists = new HashSet<TestExecutionResultBugList>(
			0);*/


	public TestExecutionResultBean() {
	}


	public Integer getTestExecutionResultId() {
		return testExecutionResultId;
	}


	public void setTestExecutionResultId(Integer testExecutionResultId) {
		this.testExecutionResultId = testExecutionResultId;
	}

/*
	public TestRunListBean getTestRunList() {
		return testRunList;
	}


	public void setTestRunList(TestRunListBean testRunList) {
		this.testRunList = testRunList;
	}


	public TestResultStatusMasterBean getTestResultStatusMaster() {
		return testResultStatusMaster;
	}


	public void setTestResultStatusMaster(
			TestResultStatusMasterBean testResultStatusMaster) {
		this.testResultStatusMaster = testResultStatusMaster;
	}


	public TestCaseListBean getTestCaseList() {
		return testCaseList;
	}


	public void setTestCaseList(TestCaseListBean testCaseList) {
		this.testCaseList = testCaseList;
	}


	public TestCaseStepsListBean getTestCaseStepsList() {
		return testCaseStepsList;
	}


	public void setTestCaseStepsList(TestCaseStepsListBean testCaseStepsList) {
		this.testCaseStepsList = testCaseStepsList;
	}*/


	public TestSuiteListBean getTestSuiteList() {
		return testSuiteList;
	}


	public void setTestSuiteList(TestSuiteListBean testSuiteList) {
		this.testSuiteList = testSuiteList;
	}


	public String getTestStep() {
		return testStep;
	}


	public void setTestStep(String testStep) {
		this.testStep = testStep;
	}


	public String getTestStepDescription() {
		return testStepDescription;
	}


	public void setTestStepDescription(String testStepDescription) {
		this.testStepDescription = testStepDescription;
	}


	public String getTestStepInput() {
		return testStepInput;
	}


	public void setTestStepInput(String testStepInput) {
		this.testStepInput = testStepInput;
	}


	public String getTestStepExpectedOutput() {
		return testStepExpectedOutput;
	}


	public void setTestStepExpectedOutput(String testStepExpectedOutput) {
		this.testStepExpectedOutput = testStepExpectedOutput;
	}


	public String getTestStepObservedOutput() {
		return testStepObservedOutput;
	}


	public void setTestStepObservedOutput(String testStepObservedOutput) {
		this.testStepObservedOutput = testStepObservedOutput;
	}


	public String getTestCase() {
		return testCase;
	}


	public void setTestCase(String testCase) {
		this.testCase = testCase;
	}


	public String getTestCaseDescription() {
		return testCaseDescription;
	}


	public void setTestCaseDescription(String testCaseDescription) {
		this.testCaseDescription = testCaseDescription;
	}


	public String getScreenShotPath() {
		return screenShotPath;
	}


	public void setScreenShotPath(String screenShotPath) {
		this.screenShotPath = screenShotPath;
	}


	public String getScreenShotLabel() {
		return screenShotLabel;
	}


	public void setScreenShotLabel(String screenShotLabel) {
		this.screenShotLabel = screenShotLabel;
	}


	public Date getStartTime() {
		return startTime;
	}


	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}


	public Date getEndTime() {
		return endTime;
	}


	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}


	public String getFailureReason() {
		return failureReason;
	}


	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}


	public String getExecutionRemarks() {
		return executionRemarks;
	}


	public void setExecutionRemarks(String executionRemarks) {
		this.executionRemarks = executionRemarks;
	}

	/*public TestExecutionResult(TestRunList testRunList,
			TestResultStatusMaster testResultStatusMaster,
			TestSuiteList testSuiteList, String testStep, String testCase) {
		this.testRunList = testRunList;
		this.testResultStatusMaster = testResultStatusMaster;
		this.testSuiteList = testSuiteList;
		this.testStep = testStep;
		this.testCase = testCase;
	}

	public TestExecutionResult(TestRunList testRunList,
			TestResultStatusMaster testResultStatusMaster,
			TestCaseList testCaseList, TestCaseStepsList testCaseStepsList,
			TestSuiteList testSuiteList, String testStep,
			String testStepDescription, String testStepInput,
			String testStepExpectedOutput, String testStepObservedOutput,
			String testCase, String testCaseDescription, String screenShotPath,
			Date startTime, Date endTime, String failureReason,
			String executionRemarks,String testRunEvidenceStatus,
			Set<TestExecutionResultBugList> testExecutionResultBugLists) {
		this.testRunList = testRunList;
		this.testResultStatusMaster = testResultStatusMaster;
		this.testCaseList = testCaseList;
		this.testCaseStepsList = testCaseStepsList;
		this.testSuiteList = testSuiteList;
		this.testStep = testStep;
		this.testStepDescription = testStepDescription;
		this.testStepInput = testStepInput;
		this.testStepExpectedOutput = testStepExpectedOutput;
		this.testStepObservedOutput = testStepObservedOutput;
		this.testCase = testCase;
		this.testCaseDescription = testCaseDescription;
		this.screenShotPath = screenShotPath;
		this.startTime = startTime;
		this.endTime = endTime;
		this.failureReason = failureReason;
		this.executionRemarks = executionRemarks;
		this.testExecutionResultBugLists = testExecutionResultBugLists;
	}*/

	

}
