package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CommonActiveStatusMaster generated by hbm2java
 */
@Entity
@Table(name = "common_active_status_master")
public class CommonActiveStatusMaster implements java.io.Serializable {

	private String status;
	private Set<UserList> userLists = new HashSet<UserList>(0);
	private Set<DeviceList> deviceLists = new HashSet<DeviceList>(0);
	private Set<HostList> hostLists = new HashSet<HostList>(0);

	public CommonActiveStatusMaster() {
	}

	public CommonActiveStatusMaster(String status) {
		this.status = status;
	}

	public CommonActiveStatusMaster(String status, Set<UserList> userLists,
			Set<DeviceList> deviceLists, Set<HostList> hostLists) {
		this.status = status;
		this.userLists = userLists;
		this.deviceLists = deviceLists;
		this.hostLists = hostLists;
	}

	@Id
	@Column(name = "status", unique = true, nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonActiveStatusMaster")
	public Set<UserList> getUserLists() {
		return this.userLists;
	}

	public void setUserLists(Set<UserList> userLists) {
		this.userLists = userLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonActiveStatusMaster")
	public Set<DeviceList> getDeviceLists() {
		return this.deviceLists;
	}

	public void setDeviceLists(Set<DeviceList> deviceLists) {
		this.deviceLists = deviceLists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commonActiveStatusMaster")
	public Set<HostList> getHostLists() {
		return this.hostLists;
	}

	public void setHostLists(Set<HostList> hostLists) {
		this.hostLists = hostLists;
	}

}
