package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeviceDetailsViewId generated by hbm2java
 */
@Embeddable
public class DeviceDetailsViewId implements java.io.Serializable {

	private String deviceMake;
	private int deviceModelListId;
	private String devicePlatformName;
	private int devicePlatformVersionListId;
	private int deviceListId;
	private String deviceId;
	private int hostId;
	private String deviceStatus;
	private String devicePlatformVersion;
	private String devicePlatformVersionDescription;
	private String deviceModel;
	private String deviceResolution;

	public DeviceDetailsViewId() {
	}

	public DeviceDetailsViewId(String deviceMake, int deviceModelListId,
			String devicePlatformName, int devicePlatformVersionListId,
			int deviceListId, String deviceId, int hostId, String deviceStatus,
			String devicePlatformVersion, String deviceModel,
			String deviceResolution) {
		this.deviceMake = deviceMake;
		this.deviceModelListId = deviceModelListId;
		this.devicePlatformName = devicePlatformName;
		this.devicePlatformVersionListId = devicePlatformVersionListId;
		this.deviceListId = deviceListId;
		this.deviceId = deviceId;
		this.hostId = hostId;
		this.deviceStatus = deviceStatus;
		this.devicePlatformVersion = devicePlatformVersion;
		this.deviceModel = deviceModel;
		this.deviceResolution = deviceResolution;
	}

	public DeviceDetailsViewId(String deviceMake, int deviceModelListId,
			String devicePlatformName, int devicePlatformVersionListId,
			int deviceListId, String deviceId, int hostId, String deviceStatus,
			String devicePlatformVersion,
			String devicePlatformVersionDescription, String deviceModel,
			String deviceResolution) {
		this.deviceMake = deviceMake;
		this.deviceModelListId = deviceModelListId;
		this.devicePlatformName = devicePlatformName;
		this.devicePlatformVersionListId = devicePlatformVersionListId;
		this.deviceListId = deviceListId;
		this.deviceId = deviceId;
		this.hostId = hostId;
		this.deviceStatus = deviceStatus;
		this.devicePlatformVersion = devicePlatformVersion;
		this.devicePlatformVersionDescription = devicePlatformVersionDescription;
		this.deviceModel = deviceModel;
		this.deviceResolution = deviceResolution;
	}

	@Column(name = "deviceMake", nullable = false, length = 60)
	public String getDeviceMake() {
		return this.deviceMake;
	}

	public void setDeviceMake(String deviceMake) {
		this.deviceMake = deviceMake;
	}

	@Column(name = "deviceModelListId", nullable = false)
	public int getDeviceModelListId() {
		return this.deviceModelListId;
	}

	public void setDeviceModelListId(int deviceModelListId) {
		this.deviceModelListId = deviceModelListId;
	}

	@Column(name = "devicePlatformName", nullable = false, length = 50)
	public String getDevicePlatformName() {
		return this.devicePlatformName;
	}

	public void setDevicePlatformName(String devicePlatformName) {
		this.devicePlatformName = devicePlatformName;
	}

	@Column(name = "devicePlatformVersionListId", nullable = false)
	public int getDevicePlatformVersionListId() {
		return this.devicePlatformVersionListId;
	}

	public void setDevicePlatformVersionListId(int devicePlatformVersionListId) {
		this.devicePlatformVersionListId = devicePlatformVersionListId;
	}

	@Column(name = "deviceListId", nullable = false)
	public int getDeviceListId() {
		return this.deviceListId;
	}

	public void setDeviceListId(int deviceListId) {
		this.deviceListId = deviceListId;
	}

	@Column(name = "deviceId", nullable = false, length = 150)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "hostId", nullable = false)
	public int getHostId() {
		return this.hostId;
	}

	public void setHostId(int hostId) {
		this.hostId = hostId;
	}

	@Column(name = "deviceStatus", nullable = false, length = 10)
	public String getDeviceStatus() {
		return this.deviceStatus;
	}

	public void setDeviceStatus(String deviceStatus) {
		this.deviceStatus = deviceStatus;
	}

	@Column(name = "devicePlatformVersion", nullable = false, length = 50)
	public String getDevicePlatformVersion() {
		return this.devicePlatformVersion;
	}

	public void setDevicePlatformVersion(String devicePlatformVersion) {
		this.devicePlatformVersion = devicePlatformVersion;
	}

	@Column(name = "devicePlatformVersionDescription", length = 100)
	public String getDevicePlatformVersionDescription() {
		return this.devicePlatformVersionDescription;
	}

	public void setDevicePlatformVersionDescription(
			String devicePlatformVersionDescription) {
		this.devicePlatformVersionDescription = devicePlatformVersionDescription;
	}

	@Column(name = "deviceModel", nullable = false, length = 30)
	public String getDeviceModel() {
		return this.deviceModel;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	@Column(name = "deviceResolution", nullable = false, length = 20)
	public String getDeviceResolution() {
		return this.deviceResolution;
	}

	public void setDeviceResolution(String deviceResolution) {
		this.deviceResolution = deviceResolution;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeviceDetailsViewId))
			return false;
		DeviceDetailsViewId castOther = (DeviceDetailsViewId) other;

		return ((this.getDeviceMake() == castOther.getDeviceMake()) || (this
				.getDeviceMake() != null && castOther.getDeviceMake() != null && this
				.getDeviceMake().equals(castOther.getDeviceMake())))
				&& (this.getDeviceModelListId() == castOther
						.getDeviceModelListId())
				&& ((this.getDevicePlatformName() == castOther
						.getDevicePlatformName()) || (this
						.getDevicePlatformName() != null
						&& castOther.getDevicePlatformName() != null && this
						.getDevicePlatformName().equals(
								castOther.getDevicePlatformName())))
				&& (this.getDevicePlatformVersionListId() == castOther
						.getDevicePlatformVersionListId())
				&& (this.getDeviceListId() == castOther.getDeviceListId())
				&& ((this.getDeviceId() == castOther.getDeviceId()) || (this
						.getDeviceId() != null
						&& castOther.getDeviceId() != null && this
						.getDeviceId().equals(castOther.getDeviceId())))
				&& (this.getHostId() == castOther.getHostId())
				&& ((this.getDeviceStatus() == castOther.getDeviceStatus()) || (this
						.getDeviceStatus() != null
						&& castOther.getDeviceStatus() != null && this
						.getDeviceStatus().equals(castOther.getDeviceStatus())))
				&& ((this.getDevicePlatformVersion() == castOther
						.getDevicePlatformVersion()) || (this
						.getDevicePlatformVersion() != null
						&& castOther.getDevicePlatformVersion() != null && this
						.getDevicePlatformVersion().equals(
								castOther.getDevicePlatformVersion())))
				&& ((this.getDevicePlatformVersionDescription() == castOther
						.getDevicePlatformVersionDescription()) || (this
						.getDevicePlatformVersionDescription() != null
						&& castOther.getDevicePlatformVersionDescription() != null && this
						.getDevicePlatformVersionDescription()
						.equals(castOther.getDevicePlatformVersionDescription())))
				&& ((this.getDeviceModel() == castOther.getDeviceModel()) || (this
						.getDeviceModel() != null
						&& castOther.getDeviceModel() != null && this
						.getDeviceModel().equals(castOther.getDeviceModel())))
				&& ((this.getDeviceResolution() == castOther
						.getDeviceResolution()) || (this.getDeviceResolution() != null
						&& castOther.getDeviceResolution() != null && this
						.getDeviceResolution().equals(
								castOther.getDeviceResolution())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDeviceMake() == null ? 0 : this.getDeviceMake()
						.hashCode());
		result = 37 * result + this.getDeviceModelListId();
		result = 37
				* result
				+ (getDevicePlatformName() == null ? 0 : this
						.getDevicePlatformName().hashCode());
		result = 37 * result + this.getDevicePlatformVersionListId();
		result = 37 * result + this.getDeviceListId();
		result = 37 * result
				+ (getDeviceId() == null ? 0 : this.getDeviceId().hashCode());
		result = 37 * result + this.getHostId();
		result = 37
				* result
				+ (getDeviceStatus() == null ? 0 : this.getDeviceStatus()
						.hashCode());
		result = 37
				* result
				+ (getDevicePlatformVersion() == null ? 0 : this
						.getDevicePlatformVersion().hashCode());
		result = 37
				* result
				+ (getDevicePlatformVersionDescription() == null ? 0 : this
						.getDevicePlatformVersionDescription().hashCode());
		result = 37
				* result
				+ (getDeviceModel() == null ? 0 : this.getDeviceModel()
						.hashCode());
		result = 37
				* result
				+ (getDeviceResolution() == null ? 0 : this
						.getDeviceResolution().hashCode());
		return result;
	}

}
