package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DevicePlatformVersionListMaster generated by hbm2java
 */
@Entity
@Table(name = "device_platform_version_list_master")
public class DevicePlatformVersionListMaster implements java.io.Serializable {

	private Integer devicePlatformVersionListId;
	private DevicePlatformMaster devicePlatformMaster;
	private String devicePlatformVersion;
	private String devicePlatformVersionDescription;
	private Set<DeviceList> deviceLists = new HashSet<DeviceList>(0);

	public DevicePlatformVersionListMaster() {
	}

	public DevicePlatformVersionListMaster(
			DevicePlatformMaster devicePlatformMaster,
			String devicePlatformVersion) {
		this.devicePlatformMaster = devicePlatformMaster;
		this.devicePlatformVersion = devicePlatformVersion;
	}

	public DevicePlatformVersionListMaster(
			DevicePlatformMaster devicePlatformMaster,
			String devicePlatformVersion,
			String devicePlatformVersionDescription,
			Set<DeviceList> deviceLists) {
		this.devicePlatformMaster = devicePlatformMaster;
		this.devicePlatformVersion = devicePlatformVersion;
		this.devicePlatformVersionDescription = devicePlatformVersionDescription;
		this.deviceLists = deviceLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "devicePlatformVersionListId", unique = true, nullable = false)
	public Integer getDevicePlatformVersionListId() {
		return this.devicePlatformVersionListId;
	}

	public void setDevicePlatformVersionListId(
			Integer devicePlatformVersionListId) {
		this.devicePlatformVersionListId = devicePlatformVersionListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "devicePlatformName", nullable = false)
	public DevicePlatformMaster getDevicePlatformMaster() {
		return this.devicePlatformMaster;
	}

	public void setDevicePlatformMaster(
			DevicePlatformMaster devicePlatformMaster) {
		this.devicePlatformMaster = devicePlatformMaster;
	}

	@Column(name = "devicePlatformVersion", nullable = false, length = 50)
	public String getDevicePlatformVersion() {
		return this.devicePlatformVersion;
	}

	public void setDevicePlatformVersion(String devicePlatformVersion) {
		this.devicePlatformVersion = devicePlatformVersion;
	}

	@Column(name = "devicePlatformVersionDescription", length = 100)
	public String getDevicePlatformVersionDescription() {
		return this.devicePlatformVersionDescription;
	}

	public void setDevicePlatformVersionDescription(
			String devicePlatformVersionDescription) {
		this.devicePlatformVersionDescription = devicePlatformVersionDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "devicePlatformVersionListMaster")
	public Set<DeviceList> getDeviceLists() {
		return this.deviceLists;
	}

	public void setDeviceLists(Set<DeviceList> deviceLists) {
		this.deviceLists = deviceLists;
	}

}
