package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeviceModelMaster generated by hbm2java
 */
@Entity
@Table(name = "device_model_master")
public class DeviceModelMaster implements java.io.Serializable {

	private Integer deviceModelListId;
	private DeviceMakeMaster deviceMakeMaster;
	private String deviceModel;
	private String deviceResolution;
	private Set<DeviceList> deviceLists = new HashSet<DeviceList>(0);
	private DeviceType deviceType;
	private String deviceName;

	public DeviceModelMaster() {
	}

	public DeviceModelMaster(DeviceMakeMaster deviceMakeMaster,
			String deviceModel, String deviceResolution) {
		this.deviceMakeMaster = deviceMakeMaster;
		this.deviceModel = deviceModel;
		this.deviceResolution = deviceResolution;
	}

	public DeviceModelMaster(DeviceMakeMaster deviceMakeMaster,
			String deviceModel, String deviceResolution,
			Set<DeviceList> deviceLists) {
		this.deviceMakeMaster = deviceMakeMaster;
		this.deviceModel = deviceModel;
		this.deviceResolution = deviceResolution;
		this.deviceLists = deviceLists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "deviceModelListId", unique = true,nullable=false)
	public Integer getDeviceModelListId() {
		return this.deviceModelListId;
	}

	public void setDeviceModelListId(Integer deviceModelListId) {
		this.deviceModelListId = deviceModelListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceMakeId",nullable=false)
	public DeviceMakeMaster getDeviceMakeMaster() {
		return this.deviceMakeMaster;
	}

	public void setDeviceMakeMaster(DeviceMakeMaster deviceMakeMaster) {
		this.deviceMakeMaster = deviceMakeMaster;
	}

	@Column(name = "deviceModel",length = 100,nullable=false)
	public String getDeviceModel() {
		return this.deviceModel;
	}

	public void setDeviceModel(String deviceModel) {
		this.deviceModel = deviceModel;
	}

	@Column(name = "deviceResolution",length = 20,nullable=false)
	public String getDeviceResolution() {
		return this.deviceResolution;
	}

	public void setDeviceResolution(String deviceResolution) {
		this.deviceResolution = deviceResolution;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceModelMaster")
	public Set<DeviceList> getDeviceLists() {
		return this.deviceLists;
	}

	public void setDeviceLists(Set<DeviceList> deviceLists) {
		this.deviceLists = deviceLists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceTypeId")
	public DeviceType getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "deviceName",length = 100)
	public String getDeviceName() {
		return deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

}
