package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DeviceDetailsView generated by hbm2java
 */
@Entity
@Table(name = "device_details_view")
public class DeviceDetailsView implements java.io.Serializable {

	private DeviceDetailsViewId id;

	public DeviceDetailsView() {
	}

	public DeviceDetailsView(DeviceDetailsViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "deviceMake", column = @Column(name = "deviceMake", nullable = false, length = 60)),
			@AttributeOverride(name = "deviceModelListId", column = @Column(name = "deviceModelListId", nullable = false)),
			@AttributeOverride(name = "devicePlatformName", column = @Column(name = "devicePlatformName", nullable = false, length = 50)),
			@AttributeOverride(name = "devicePlatformVersionListId", column = @Column(name = "devicePlatformVersionListId", nullable = false)),
			@AttributeOverride(name = "deviceListId", column = @Column(name = "deviceListId", nullable = false)),
			@AttributeOverride(name = "deviceId", column = @Column(name = "deviceId", nullable = false, length = 150)),
			@AttributeOverride(name = "hostId", column = @Column(name = "hostId", nullable = false)),
			@AttributeOverride(name = "deviceStatus", column = @Column(name = "deviceStatus", nullable = false, length = 10)),
			@AttributeOverride(name = "devicePlatformVersion", column = @Column(name = "devicePlatformVersion", nullable = false, length = 50)),
			@AttributeOverride(name = "devicePlatformVersionDescription", column = @Column(name = "devicePlatformVersionDescription", length = 100)),
			@AttributeOverride(name = "deviceModel", column = @Column(name = "deviceModel", nullable = false, length = 30)),
			@AttributeOverride(name = "deviceResolution", column = @Column(name = "deviceResolution", nullable = false, length = 20)) })
	public DeviceDetailsViewId getId() {
		return this.id;
	}

	public void setId(DeviceDetailsViewId id) {
		this.id = id;
	}

}
