package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeviceMakeMaster generated by hbm2java
 */
@Entity
@Table(name = "device_make_master")
public class DeviceMakeMaster implements java.io.Serializable {

	private String deviceMake;
	private Integer deviceMakeId;
	
	private Set<DeviceModelMaster> deviceModelMasters = new HashSet<DeviceModelMaster>(
			0);

	public DeviceMakeMaster() {
	}

	public DeviceMakeMaster(String deviceMake) {
		this.deviceMake = deviceMake;
	}

	public DeviceMakeMaster(String deviceMake,
			Set<DeviceModelMaster> deviceModelMasters) {
		this.deviceMake = deviceMake;
		this.deviceModelMasters = deviceModelMasters;
	}

	@Column(name = "deviceMake", length = 60)
	public String getDeviceMake() {
		return this.deviceMake;
	}

	public void setDeviceMake(String deviceMake) {
		this.deviceMake = deviceMake;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceMakeMaster")
	public Set<DeviceModelMaster> getDeviceModelMasters() {
		return this.deviceModelMasters;
	}

	public void setDeviceModelMasters(Set<DeviceModelMaster> deviceModelMasters) {
		this.deviceModelMasters = deviceModelMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "deviceMakeId", unique = true, nullable = false)
	public Integer getDeviceMakeId() {
		return deviceMakeId;
	}

	public void setDeviceMakeId(Integer deviceMakeId) {
		this.deviceMakeId = deviceMakeId;
	}
	
	

}
