package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestEnviromentMaster generated by hbm2java
 */
@Entity
@Table(name = "tfwp_test_environment")
public class Environment implements java.io.Serializable {

	private Integer environmentId;
	private String environmentName;
	private String description;
	private Integer isStandAloneEnvironment;
	private Date createdDate;
	private Date modifiedDate;
	private Integer status;
	private ProductMaster productMaster;
	private Set<WorkPackage> workPackageList = new HashSet<WorkPackage>(0);
	private EnvironmentCategory  environmentCategory;
	private Set<EnvironmentCombination> environmentCombinationSet = new HashSet<EnvironmentCombination>(0);
	
	public Environment() {
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "environmentId", unique = true, nullable = false)
	public Integer getEnvironmentId() {
		return this.environmentId;
	}

	public void setEnvironmentId(Integer environmentId) {
		this.environmentId = environmentId;
	}
	
	@Column(name = "environmentName", length = 100)
	public String getEnvironmentName() {
		return environmentName;
	}

	public void setEnvironmentName(String environmentName) {
		this.environmentName = environmentName;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedDate")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId")
	public ProductMaster getProductMaster() {
		return productMaster;
	}

	public void setProductMaster(ProductMaster productMaster) {
		this.productMaster = productMaster;
	}
	
	@Override
	public boolean equals(Object o) {
		
		Environment e = (Environment) o;
		if (this.environmentId == e.getEnvironmentId())
			return true;
		else
			return false;
	}
	
	@Override
	public int hashCode(){
	    return (int) environmentId;
	  }
	
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "environmentList",cascade=CascadeType.ALL)
	public Set<WorkPackage> getWorkPackageList() {
		return workPackageList;
	}

	public void setWorkPackageList(Set<WorkPackage> workPackageList) {
		this.workPackageList = workPackageList;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "environmentCategoryId") 
	public EnvironmentCategory getEnvironmentCategory() {
		return environmentCategory;
	}

	public void setEnvironmentCategory(EnvironmentCategory environmentCategory) {
		this.environmentCategory = environmentCategory;
	}
	
	private Set<WorkPackageTestCaseExecutionPlan> workPackageTestCaseExecutionPlanList = new HashSet<WorkPackageTestCaseExecutionPlan>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "workpackagetestcaseexecutionplan_has_environment", joinColumns = { @JoinColumn(name = "environmentId") }, inverseJoinColumns = { @JoinColumn(name = "id") })
	public Set<WorkPackageTestCaseExecutionPlan> getWorkPackageTestCaseExecutionPlanList() {
		return workPackageTestCaseExecutionPlanList;
	}

	public void setWorkPackageTestCaseExecutionPlanList(
			Set<WorkPackageTestCaseExecutionPlan> workPackageTestCaseExecutionPlanList) {
		this.workPackageTestCaseExecutionPlanList = workPackageTestCaseExecutionPlanList;
	}
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "environmentSet",cascade=CascadeType.ALL)
	public Set<EnvironmentCombination> getEnvironmentCombinationSet() {
		return environmentCombinationSet;
	}

	public void setEnvironmentCombinationSet(Set<EnvironmentCombination> environmentCombinationSet) {
		this.environmentCombinationSet = environmentCombinationSet;
	}

	@Column(name = "isStandAloneEnvironment")
	public Integer getIsStandAloneEnvironment() {
		return isStandAloneEnvironment;
	}

	public void setIsStandAloneEnvironment(Integer isStandAloneEnvironment) {
		this.isStandAloneEnvironment = isStandAloneEnvironment;
	}
	
}
