package com.hcl.atf.taf.model;

import static javax.persistence.GenerationType.IDENTITY;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Event  - ATF Event Object.
 */
@Entity
@Table(name = "common_events")
public class Event {

	public Integer eventId; // Autogenerated
	public String eventSourceComponent; // Referenced Constant
	public String eventName; // Referenced Constant
	public String eventDescription; // User provided
	public Double eventData; // Primary metric related to event
	public Double additonalEventData; // Metric related to event
	public Double additonalEventData2; // Metric related to event
	public String eventCategory; // Referenced Constant
	public String eventType; // Referenced Constant
	public String sourceEntityType; // Referenced Constant
	public Integer sourceEntityId; // Entity Reference from source System
	public String sourceEntityName; // Entity Reference from source System
	public String targetEntityType; // Referenced Constant
	public Integer targetEntityId; // Entity Reference from source System
	public String targetEntityName; // Entity Reference from source System
	public String additionalTargetEntityType; // Referenced Constant
	public Integer additionalTargetEntityId; // Entity Reference from source System
	public String additionalTargetEntityName; // Entity Reference from source System
	public Integer eventStatus; //Open(0) or closed(1) event
	public Date startTime;
	public Date endTime;
	public Integer userId;
	public String userName;
	public Integer roleId;
	public String roleLabel;
	public String fieldName;
	public String fieldValue;
	public String newFieldValue;
	
	public Event() {
		
	}
	
	public Event(
			String eventSourceComponent,
			String eventName, String eventDescription, 
			Double eventData, Double additonalEventData, Double additonalEventData2, 
			String eventCategory, String eventType,
			String sourceEntityType, Integer sourceEntityId, String sourceEntityName,
			String targetEntityType, Integer targetEntityId, String targetEntityName,
			String additionalTargetEntityType, Integer additionalTargetEntityId, String additionalTargetEntityName, 
			Integer eventStatus,
			Date startTime, Date endTime) {

		this.eventSourceComponent = eventSourceComponent;
		this.eventName = eventName;
		this.eventDescription = eventDescription;
		this.eventData = eventData;
		this.additonalEventData = additonalEventData;
		this.additonalEventData2 = additonalEventData2;
		this.eventCategory = eventCategory;
		this.eventType = eventType;
		this.sourceEntityType = sourceEntityType;
		this.sourceEntityId = sourceEntityId;
		this.sourceEntityName = sourceEntityName;
		this.targetEntityType = targetEntityType;
		this.targetEntityId = targetEntityId;
		this.targetEntityName = targetEntityName;
		this.additionalTargetEntityType = additionalTargetEntityType;
		this.additionalTargetEntityId = additionalTargetEntityId;
		this.additionalTargetEntityName = additionalTargetEntityName;
		this.eventStatus = eventStatus;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "eventId", unique = true, nullable = false)
	public Integer getEventId() {
		return eventId;
	}
	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "eventSourceComponent")
	public String getEventSourceComponent() {
		return eventSourceComponent;
	}
	public void setEventSourceComponent(String eventSourceComponent) {
		this.eventSourceComponent = eventSourceComponent;
	}
	@Column(name = "eventName")
	public String getEventName() {
		return eventName;
	}
	public void setEventName(String eventName) {
		this.eventName = eventName;
	}
	@Column(name = "eventDescription")
	public String getEventDescription() {
		return eventDescription;
	}
	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}
	@Column(name = "eventData")
	public Double getEventData() {
		return eventData;
	}
	public void setEventData(Double eventData) {
		this.eventData = eventData;
	}
	@Column(name = "additonalEventData")
	public Double getAdditonalEventData() {
		return additonalEventData;
	}
	public void setAdditonalEventData(Double additonalEventData) {
		this.additonalEventData = additonalEventData;
	}
	@Column(name = "additonalEventData2")
	public Double getAdditonalEventData2() {
		return additonalEventData2;
	}
	public void setAdditonalEventData2(Double additonalEventData2) {
		this.additonalEventData2 = additonalEventData2;
	}
	@Column(name = "eventCategory")
	public String getEventCategory() {
		return eventCategory;
	}
	public void setEventCategory(String eventCategory) {
		this.eventCategory = eventCategory;
	}
	@Column(name = "eventType")
	public String getEventType() {
		return eventType;
	}
	public void setEventType(String eventType) {
		this.eventType = eventType;
	}
	@Column(name = "sourceEntityType")
	public String getSourceEntityType() {
		return sourceEntityType;
	}
	public void setSourceEntityType(String sourceEntityType) {
		this.sourceEntityType = sourceEntityType;
	}
	@Column(name = "sourceEntityId")
	public Integer getSourceEntityId() {
		return sourceEntityId;
	}
	public void setSourceEntityId(Integer sourceEntityId) {
		this.sourceEntityId = sourceEntityId;
	}
	@Column(name = "sourceEntityName")
	public String getSourceEntityName() {
		return sourceEntityName;
	}
	public void setSourceEntityName(String sourceEntityName) {
		this.sourceEntityName = sourceEntityName;
	}
	@Column(name = "targetEntityType")
	public String getTargetEntityType() {
		return targetEntityType;
	}
	public void setTargetEntityType(String targetEntityType) {
		this.targetEntityType = targetEntityType;
	}
	@Column(name = "targetEntityId")
	public Integer getTargetEntityId() {
		return targetEntityId;
	}
	public void setTargetEntityId(Integer targetEntityId) {
		this.targetEntityId = targetEntityId;
	}
	@Column(name = "targetEntityName")
	public String getTargetEntityName() {
		return targetEntityName;
	}
	public void setTargetEntityName(String targetEntityName) {
		this.targetEntityName = targetEntityName;
	}
	@Column(name = "additionalTargetEntityType")
	public String getAdditionalTargetEntityType() {
		return additionalTargetEntityType;
	}
	public void setAdditionalTargetEntityType(String additionalTargetEntityType) {
		this.additionalTargetEntityType = additionalTargetEntityType;
	}
	@Column(name = "additionalTargetEntityId")
	public Integer getAdditionalTargetEntityId() {
		return additionalTargetEntityId;
	}
	public void setAdditionalTargetEntityId(Integer additionalTargetEntityId) {
		this.additionalTargetEntityId = additionalTargetEntityId;
	}
	@Column(name = "additionalTargetEntityName")
	public String getAdditionalTargetEntityName() {
		return additionalTargetEntityName;
	}
	public void setAdditionalTargetEntityName(String additionalTargetEntityName) {
		this.additionalTargetEntityName = additionalTargetEntityName;
	}
	@Column(name = "eventStatus")
	public Integer getEventStatus() {
		return eventStatus;
	}
	public void setEventStatus(Integer eventStatus) {
		this.eventStatus = eventStatus;
	}
	@Column(name = "startTime")
	public Date getStartTime() {
		return startTime;
	}
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	@Column(name = "endTime")
	public Date getEndTime() {
		return endTime;
	}
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "userId")
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "userName")
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleLabel")
	public String getRoleLabel() {
		return roleLabel;
	}

	public void setRoleLabel(String roleLabel) {
		this.roleLabel = roleLabel;
	}

	@Column(name = "fieldName")
	public String getFieldName() {
		return fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "fieldValue")
	public String getFieldValue() {
		return fieldValue;
	}

	public void setFieldValue(String fieldValue) {
		this.fieldValue = fieldValue;
	}

	@Column(name = "newFieldValue")
	public String getNewFieldValue() {
		return newFieldValue;
	}

	public void setNewFieldValue(String newFieldValue) {
		this.newFieldValue = newFieldValue;
	}
}
