package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * evidence_type generated by hbm2java
 */
@Entity
@Table(name = "evidence_type")
public class EvidenceType implements java.io.Serializable {

	private Integer evidenceTypeId;
	private String evidenceTypeName;
	private String description;


	public EvidenceType() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "evidenceTypeId", unique = true, nullable = false)
	public Integer getEvidenceTypeId() {
		return evidenceTypeId;
	}

	public void setEvidenceTypeId(Integer evidenceTypeId) {
		this.evidenceTypeId = evidenceTypeId;
	}

	@Column(name = "evidenceTypeName")
	public String getEvidenceTypeName() {
		return evidenceTypeName;
	}


	public void setEvidenceTypeName(String evidenceTypeName) {
		this.evidenceTypeName = evidenceTypeName;
	}


	

	@Column(name = "description")
	public String getDescription() {
		return description;
	}


	public void setDescription(String description) {
		this.description = description;
	}

	
}
