package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * UserList generated by hbm2java
 */
@Entity
@Table(name = "execution_mode")
public class ExecutionMode implements java.io.Serializable {
	private Integer modeId;	
	private String name;
	private Set<TestToolMaster> testEngines = new HashSet<TestToolMaster>(0);
	public ExecutionMode() {
	}

	
		
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "modeId", unique = true, nullable = false)

	public Integer getModeId() {
		return modeId;
	}

	public void setModeId(Integer modeId) {
		this.modeId = modeId;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "executionModes",cascade=CascadeType.ALL)
	public Set<TestToolMaster> getTestEngines() {
		return testEngines;
	}

	public void setTestEngines(Set<TestToolMaster> testEngines) {
		this.testEngines = testEngines;
	}

	@Override
	public boolean equals(Object o) {
		Languages lang = (Languages) o;
		if (this.modeId == lang.getId()) {
			return true;
		}else{
			return false;
		}
	}
	
	@Override
	public int hashCode(){
	    return (int) modeId;
	  }
	
}
