package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HostPlatformMaster generated by hbm2java
 */
@Entity
@Table(name = "host_platform_master")
public class HostPlatformMaster implements java.io.Serializable {

	private String hostPlatform;
	private Set<HostList> hostLists = new HashSet<HostList>(0);

	public HostPlatformMaster() {
	}

	public HostPlatformMaster(String hostPlatform) {
		this.hostPlatform = hostPlatform;
	}

	public HostPlatformMaster(String hostPlatform, Set<HostList> hostLists) {
		this.hostPlatform = hostPlatform;
		this.hostLists = hostLists;
	}

	@Id
	@Column(name = "hostPlatform", unique = true, nullable = false, length = 20)
	public String getHostPlatform() {
		return this.hostPlatform;
	}

	public void setHostPlatform(String hostPlatform) {
		this.hostPlatform = hostPlatform;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hostPlatformMaster")
	public Set<HostList> getHostLists() {
		return this.hostLists;
	}

	public void setHostLists(Set<HostList> hostLists) {
		this.hostLists = hostLists;
	}

}
