package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HostHeartbeat generated by hbm2java
 */
@Entity
@Table(name = "host_heartbeat")
public class HostHeartbeat implements java.io.Serializable {

	private int hostId;
	private long lastHeartPulseReceivedTime;
	private boolean hasResponse;
	private short responseToSend;

	public HostHeartbeat() {
	}

	public HostHeartbeat(int hostId, long lastHeartPulseReceivedTime,
			boolean hasResponse, short responseToSend) {
		this.hostId = hostId;
		this.lastHeartPulseReceivedTime = lastHeartPulseReceivedTime;
		this.hasResponse = hasResponse;
		this.responseToSend = responseToSend;
	}

	@Id
	@Column(name = "hostId", unique = true, nullable = false)
	public int getHostId() {
		return this.hostId;
	}

	public void setHostId(int hostId) {
		this.hostId = hostId;
	}

	@Column(name = "lastHeartPulseReceivedTime", nullable = false)
	public long getLastHeartPulseReceivedTime() {
		return this.lastHeartPulseReceivedTime;
	}

	public void setLastHeartPulseReceivedTime(long lastHeartPulseReceivedTime) {
		this.lastHeartPulseReceivedTime = lastHeartPulseReceivedTime;
	}

	@Column(name = "hasResponse", nullable = false)
	public boolean isHasResponse() {
		return this.hasResponse;
	}

	public void setHasResponse(boolean hasResponse) {
		this.hasResponse = hasResponse;
	}

	@Column(name = "responseToSend", nullable = false)
	public short getResponseToSend() {
		return this.responseToSend;
	}

	public void setResponseToSend(short responseToSend) {
		this.responseToSend = responseToSend;
	}

}
