package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.hcl.atf.taf.model.ExecutionMode;
import com.hcl.atf.taf.model.TestToolMaster;

/**
 * UserList generated by hbm2java
 */
@Entity
@Table(name = "languages")
public class Languages implements java.io.Serializable {
	private Integer id;	
	private String name;	
	private String country;
	private Integer status;
	private Set<TestToolMaster> testEngines = new HashSet<TestToolMaster>(0);
	private Set<ExecutionMode> executionModes = new HashSet<ExecutionMode>(0);

	public Languages() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "languageId", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "country")
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@ManyToMany(fetch=FetchType.EAGER, cascade={CascadeType.ALL})
	@JoinTable(name = "testengine_language_mode", joinColumns = { @JoinColumn(name = "languageId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "testToolId", nullable = false, updatable = false) })
	public Set<TestToolMaster> getTestEngines() {
		return testEngines;
	}

	public void setTestEngines(Set<TestToolMaster> testEngines) {
		this.testEngines = testEngines;
	}
	@ManyToMany(fetch=FetchType.EAGER, cascade={CascadeType.ALL})
	@JoinTable(name = "testengine_language_mode", joinColumns = { @JoinColumn(name = "languageId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "modeId", nullable = false, updatable = false) })
	public Set<ExecutionMode> getExecutionModes() {
		return executionModes;
	}

	public void setExecutionModes(Set<ExecutionMode> executionModes) {
		this.executionModes = executionModes;
	}
	@Override
	public boolean equals(Object o) {
		Languages lang = (Languages) o;
		if (this.id == lang.getId()) {
			return true;
		}else{
			return false;
		}
	}

	@Override
	public int hashCode(){
		return (int) id;
	}
	
}
