package com.hcl.atf.taf.model;


// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductMaster generated by hbm2java
 */
@Entity
@Table(name = "product_user_roles")
public class ProductUserRole implements java.io.Serializable {

	private Integer productUserRoleId;
	private Integer status;
	
	private String name;
	private String description;
	private Date createdDate;
	private Date modifiedDate;
	
	private ProductMaster product;
	private UserList user;
	private UserRoleMaster role;
	
	public ProductUserRole() {
	}

	public ProductUserRole(String roleName, String roleLable,String description,Integer status) {
		
		this.description=description;
		this.status=status;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "productUserRoleId", unique = true, nullable = false)	
	public Integer getProductUserRoleId() {
		return productUserRoleId;
	}

	public void setProductUserRoleId(Integer productUserRoleId) {
		this.productUserRoleId = productUserRoleId;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name="createDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	@Column(name="modifiedDate")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId") 
	public ProductMaster getProduct() {
		return product;
	}

	public void setProduct(ProductMaster product) {
		this.product = product;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId") 
	public UserList getUser() {
		return user;
	}

	public void setUser(UserList user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleId") 
	public UserRoleMaster getRole() {
		return role;
	}

	public void setRole(UserRoleMaster role) {
		this.role = role;
	}

	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
}
