package com.hcl.atf.taf.model;


// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductMaster generated by hbm2java
 */
@Entity
@Table(name = "product_mode")
public class ProductMode implements java.io.Serializable {

	@Column(name = "modeId")
	private Integer modeId;
	
	@Column(name = "modeName")
	private String modeName;
	
	@Column(name = "modeDescription")
	private String modeDescription;

	@Column(name = "status")
	private Integer status;
	
	public ProductMode() {
	}

	public ProductMode(String modeName) {
		this.modeName = modeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "modeId", unique = true, nullable = false)
	public Integer getModeId() {
		return this.modeId;
	}

	public void setModeId(Integer modeId) {
		this.modeId = modeId;
	}

	@Column(name = "modeName", length = 100)
	public String getModeName() {
		return modeName;
	}

	public void setModeName(String modeName) {
		this.modeName = modeName;
	}

	@Column(name = "modeDescription", length = 100)
	public String getModeDescription() {
		return modeDescription;
	}

	public void setModeDescription(String modeDescription) {
		this.modeDescription = modeDescription;
	}

	public Integer getStatus() {
		return status;
	}

	@Column(name = "status")
	public void setStatus(Integer status) {
		this.status = status;
	}

	
	
}
