package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScriptTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "script_type_master")
public class ScriptTypeMaster implements java.io.Serializable {

	private String scriptType;
	private Set<TestSuiteList> testSuiteLists = new HashSet<TestSuiteList>(0);

	public ScriptTypeMaster() {
	}

	public ScriptTypeMaster(String scriptType) {
		this.scriptType = scriptType;
	}

	public ScriptTypeMaster(String scriptType, Set<TestSuiteList> testSuiteLists) {
		this.scriptType = scriptType;
		this.testSuiteLists = testSuiteLists;
	}

	@Id
	@Column(name = "scriptType", unique = true, nullable = false, length = 50)
	public String getScriptType() {
		return this.scriptType;
	}

	public void setScriptType(String scriptType) {
		this.scriptType = scriptType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scriptTypeMaster")
	public Set<TestSuiteList> getTestSuiteLists() {
		return this.testSuiteLists;
	}

	public void setTestSuiteLists(Set<TestSuiteList> testSuiteLists) {
		this.testSuiteLists = testSuiteLists;
	}

}
