package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestRunSelectedDeviceList generated by hbm2java
 */
@Entity
@Table(name = "test_run_selected_device_list")
public class TestRunSelectedDeviceList implements java.io.Serializable {

	private Integer selectedDeviceListId;
	private DeviceList deviceList;
	private TestRunConfigurationChild testRunConfigurationChild;

	public TestRunSelectedDeviceList() {
	}

	public TestRunSelectedDeviceList(DeviceList deviceList,
			TestRunConfigurationChild testRunConfigurationChild) {
		this.deviceList = deviceList;
		this.testRunConfigurationChild = testRunConfigurationChild;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "selectedDeviceListId", unique = true, nullable = false)
	public Integer getSelectedDeviceListId() {
		return this.selectedDeviceListId;
	}

	public void setSelectedDeviceListId(Integer selectedDeviceListId) {
		this.selectedDeviceListId = selectedDeviceListId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceListId", nullable = false)
	public DeviceList getDeviceList() {
		return this.deviceList;
	}

	public void setDeviceList(DeviceList deviceList) {
		this.deviceList = deviceList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testRunConfigurationChildId", nullable = false)
	public TestRunConfigurationChild getTestRunConfigurationChild() {
		return this.testRunConfigurationChild;
	}

	public void setTestRunConfigurationChild(
			TestRunConfigurationChild testRunConfigurationChild) {
		this.testRunConfigurationChild = testRunConfigurationChild;
	}

}
