package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.hcl.atf.taf.model.ExecutionMode;
import com.hcl.atf.taf.model.Languages;
import com.hcl.atf.taf.model.ProductType;

/**
 * TestToolMaster generated by hbm2java
 */
@Entity
@Table(name = "test_tool_master")
public class TestToolMaster implements java.io.Serializable {

	private Integer testToolId;
	private String testToolName;
	private Set<ExecutionMode> executionModes = new HashSet<ExecutionMode>(0);
	private Set<Languages> languages = new HashSet<Languages>(0);
	private Set<ProductType> productTypeSet = new HashSet<ProductType>(0);
	public TestToolMaster() {
	}

	public TestToolMaster(String testToolName) {
		this.testToolName = testToolName;
	}

	public TestToolMaster(String testToolName,
			Set<TestEnviromentMaster> testEnviromentMasters) {
		this.testToolName = testToolName;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testToolId", unique = true, nullable = false)
	public Integer getTestToolId() {
		return testToolId;
	}

	public void setTestToolId(Integer testToolId) {
		this.testToolId = testToolId;
	}
	@Column(name = "testToolName", nullable = false, length = 80)
	public String getTestToolName() {
		return this.testToolName;
	}

	public void setTestToolName(String testToolName) {
		this.testToolName = testToolName;
	}

	@ManyToMany(fetch=FetchType.EAGER, cascade={CascadeType.ALL})
	@JoinTable(name = "testengine_language_mode", joinColumns = { @JoinColumn(name = "testToolId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "modeId", nullable = false, updatable = false) })
	public Set<ExecutionMode> getExecutionModes() {
		return executionModes;
	}

	public void setExecutionModes(Set<ExecutionMode> executionModes) {
		this.executionModes = executionModes;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "testEngines",cascade=CascadeType.ALL)
	public Set<Languages> getLanguages() {
		return languages;
	}

	public void setLanguages(Set<Languages> languages) {
		this.languages = languages;
	}   

	@ManyToMany(fetch=FetchType.LAZY, mappedBy="testToolMaster", cascade={CascadeType.ALL})
	public Set<ProductType> getProductTypeSet() {
		return productTypeSet;
	}

	public void setProductTypeSet(Set<ProductType> productTypeSet) {
		this.productTypeSet = productTypeSet;
	}



}
