package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestCategoryMaster generated by hbm2java
 */
@Entity
@Table(name = "test_category_master")
public class TestCategoryMaster implements java.io.Serializable {

	private String testCategory;
	private Set<TestRunConfigurationChild> testRunConfigurationChilds = new HashSet<TestRunConfigurationChild>(
			0);

	public TestCategoryMaster() {
	}

	public TestCategoryMaster(String testCategory) {
		this.testCategory = testCategory;
	}

	public TestCategoryMaster(String testCategory,
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.testCategory = testCategory;
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

	@Id
	@Column(name = "testCategory", unique = true, nullable = false, length = 50)
	public String getTestCategory() {
		return this.testCategory;
	}

	public void setTestCategory(String testCategory) {
		this.testCategory = testCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testCategoryMaster")
	public Set<TestRunConfigurationChild> getTestRunConfigurationChilds() {
		return this.testRunConfigurationChilds;
	}

	public void setTestRunConfigurationChilds(
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

}
