package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestCaseList generated by hbm2java
 */
@Entity
@Table(name = "test_factory_resource_pool")
public class TestfactoryResourcePool implements java.io.Serializable {

	private Integer resourcePoolId;	
	private String resourcePoolName;
	private String displayName;
	private String description;
	private Integer status;
	private Date createdDate;
	private Date modifiedDate;
	private String city;
	private String state;
	private String country;	
	private TestFactoryLab testFactoryLab;
	
	private Set<TestFactory> testFactoryList = new HashSet<TestFactory>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "test_factory_resource_pool_has_test_factory", joinColumns = { @JoinColumn(name = "resourcePoolId") }, inverseJoinColumns = { @JoinColumn(name = "testFactoryId") })
	public Set<TestFactory> getTestFactoryList() {
		return testFactoryList;
	}

	public void setTestFactoryList(Set<TestFactory> testFactoryList) {
		this.testFactoryList = testFactoryList;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testFactoryLabId")
	public TestFactoryLab getTestFactoryLab() {
		return testFactoryLab;
	}
	public void setTestFactoryLab(TestFactoryLab testFactoryLab) {
		this.testFactoryLab = testFactoryLab;
	}

	public TestfactoryResourcePool() {
	}

	public TestfactoryResourcePool(TestFactoryLab testFactoryLab, int resourcePoolId, String resourcePoolName,
			String displayName, String description, int status,
			String city, String state, String country ) {
		this.testFactoryLab = testFactoryLab;
		this.resourcePoolId = resourcePoolId;
		this.resourcePoolName = resourcePoolName;
		this.displayName = displayName;
		this.description = description;
		this.status = status;
		this.city = city;
		this.state = state;
		this.country = country;		
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resourcePoolId", unique = true, nullable = false)
	public Integer getResourcePoolId() {
		return resourcePoolId;
	}

	public void setResourcePoolId(Integer resourcePoolId) {
		this.resourcePoolId = resourcePoolId;
	}

	@Column(name = "resourcePoolName", length = 250)
	public String getResourcePoolName() {
		return resourcePoolName;
	}

	public void setResourcePoolName(String resourcePoolName) {
		this.resourcePoolName = resourcePoolName;
	}

	@Column(name = "displayName", length = 2000)
	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}
	
	@Column(name = "description", length = 2000)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}	
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@Column(name = "city", length = 30)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	
	@Column(name = "state", length = 30)
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}
	
	@Column(name = "country", length = 30)
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modifiedDate")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	
	
	@Override
	public boolean equals(Object o) {
		TestfactoryResourcePool testfactoryResourcePool = (TestfactoryResourcePool) o;
		if (this.resourcePoolId == testfactoryResourcePool.getResourcePoolId()) {
			return true;
		}else{
			return false;
		}
	}
	
	@Override
	public int hashCode(){
	    return (int) resourcePoolId;
	  }


}
