package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestRunConfigurationParent generated by hbm2java
 */
@Entity
@Table(name = "test_run_configuration_parent")
public class TestRunConfigurationParent implements java.io.Serializable {

	private Integer testRunConfigurationParentId;
	private ProductMaster productMaster;
	private UserList userList;
	private String testRunconfigurationName;
	private String testRunConfigurationDescription;
	private Set<TestRunConfigurationChild> testRunConfigurationChilds = new HashSet<TestRunConfigurationChild>(
			0);

	public TestRunConfigurationParent() {
	}

	public TestRunConfigurationParent(ProductMaster productMaster,
			UserList userList, String testRunconfigurationName) {
		this.productMaster = productMaster;
		this.userList = userList;
		this.testRunconfigurationName = testRunconfigurationName;
	}

	public TestRunConfigurationParent(ProductMaster productMaster,
			UserList userList, String testRunconfigurationName,
			String testRunConfigurationDescription,
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.productMaster = productMaster;
		this.userList = userList;
		this.testRunconfigurationName = testRunconfigurationName;
		this.testRunConfigurationDescription = testRunConfigurationDescription;
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testRunConfigurationParentId", unique = true, nullable = false)
	public Integer getTestRunConfigurationParentId() {
		return this.testRunConfigurationParentId;
	}

	public void setTestRunConfigurationParentId(
			Integer testRunConfigurationParentId) {
		this.testRunConfigurationParentId = testRunConfigurationParentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public ProductMaster getProductMaster() {
		return this.productMaster;
	}

	public void setProductMaster(ProductMaster productMaster) {
		this.productMaster = productMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserList getUserList() {
		return this.userList;
	}

	public void setUserList(UserList userList) {
		this.userList = userList;
	}

	@Column(name = "testRunconfigurationName", nullable = false, length = 80)
	public String getTestRunconfigurationName() {
		return this.testRunconfigurationName;
	}

	public void setTestRunconfigurationName(String testRunconfigurationName) {
		this.testRunconfigurationName = testRunconfigurationName;
	}

	@Column(name = "testRunConfigurationDescription", length = 200)
	public String getTestRunConfigurationDescription() {
		return this.testRunConfigurationDescription;
	}

	public void setTestRunConfigurationDescription(
			String testRunConfigurationDescription) {
		this.testRunConfigurationDescription = testRunConfigurationDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testRunConfigurationParent")
	public Set<TestRunConfigurationChild> getTestRunConfigurationChilds() {
		return this.testRunConfigurationChilds;
	}

	public void setTestRunConfigurationChilds(
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

}
