package com.hcl.atf.taf.model;

// Generated May 07, 2017 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserList generated by hbm2java
 */
@Entity
@Table(name = "testengine_language_mode")
public class TestEngineLanguageMode implements java.io.Serializable {
	
	private Integer testEngineLanguageModeId;	
	private ExecutionMode executionMode;	
	
	private TestToolMaster testTool;
	private Languages language;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testEngineLanguageModeId", unique = true, nullable = false)
	public Integer getTestEngineLanguageModeId() {
		return testEngineLanguageModeId;
	}

	public void setTestEngineLanguageModeId(Integer testEngineLanguageModeId) {
		this.testEngineLanguageModeId = testEngineLanguageModeId;
	}
   

	public TestEngineLanguageMode() {
	}

	@ManyToOne
	@JoinColumn(name="modeId")
	public ExecutionMode getExecutionMode() {
		return executionMode;
	}

	public void setExecutionMode(ExecutionMode executionMode) {
		this.executionMode = executionMode;
	}
	
	@ManyToOne
	@JoinColumn(name="testToolId")
	public TestToolMaster getTestTool() {
		return testTool;
	}

	public void setTestTool(TestToolMaster testTool) {
		this.testTool = testTool;
	}
	
	@ManyToOne
	@JoinColumn(name="languageId")
	public Languages getLanguage() {
		return language;
	}

	public void setLanguage(Languages language) {
		this.language = language;
	}
	

}