package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestEnvironmentDevices generated by hbm2java
 */
@Entity
@Table(name = "test_environment_devices")
public class TestEnvironmentDevices implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer testEnvironmentDevicesId;
	private String name;
	private String description;
	private Integer status;
	private Date statusChangeDate;
	private Set<TestRunConfigurationChild> testRunConfigurationChilds = new HashSet<TestRunConfigurationChild>(
			0);
	private Set<DeviceList> deviceList = new HashSet<DeviceList>(0);
	
	
	public TestEnvironmentDevices() {
	}

	public TestEnvironmentDevices(String name, String description,
			Set<TestRunConfigurationChild> testRunConfigurationChilds,
			Set<DeviceList> deviceLists) {
		this.name = name;
		this.description = description;
		this.testRunConfigurationChilds = testRunConfigurationChilds;
		this.deviceList = deviceLists;	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testEnvironmentDevicesId", unique = true, nullable = false)
	public Integer getTestEnvironmentDevicesId() {
		return this.testEnvironmentDevicesId;
	}

	public void setTestEnvironmentDevicesId(Integer testEnvironmentDevicesId) {
		this.testEnvironmentDevicesId = testEnvironmentDevicesId;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusChangeDate")
	public Date getStatusChangeDate() {
		return this.statusChangeDate;
	}

	public void setStatusChangeDate(Date statusChangeDate) {
		this.statusChangeDate = statusChangeDate;
	}
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "testEnvironmentDeviceses")
	public Set<TestRunConfigurationChild> getTestRunConfigurationChilds() {
		return this.testRunConfigurationChilds;
	}

	public void setTestRunConfigurationChilds(
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "test_environment_devices_has_device_list", joinColumns = { @JoinColumn(name = "testEnvironmentDevicesId") }, inverseJoinColumns = { @JoinColumn(name = "deviceListId") })
	public Set<DeviceList> getDeviceList() {
		return this.deviceList;
	}

	public void setDeviceList(Set<DeviceList> deviceList) {
		this.deviceList = deviceList;
	}	
}
