package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestExecutionResult generated by hbm2java
 */
@Entity
@Table(name = "teststep_execution_result")
public class TestStepExecutionResult implements java.io.Serializable {

	private Integer teststepexecutionresultid;
	private String result;
	private TestCaseExecutionResult testCaseExecutionResult;
	private String comments;
	private Integer isApproved;
	private Integer isReviewed;
	private String observedOutput;
	private TestCaseStepsList testSteps;
	private TestCaseList testcase;
	
	private Date testStepStarttime; 
	private Date testStepEndtime; 
	private String failureReason;
	private String testStepExpectedOutput;
	private String testStepInput;
	
	private EnvironmentCombination environmentCombination;
	private TestRunJob testJob;
	private String evidencePath;
	
	
	public TestStepExecutionResult() {
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "teststepexecutionresultid", unique = true, nullable = false)
	public Integer getTeststepexecutionresultid() {
		return teststepexecutionresultid;
	}

	public void setTeststepexecutionresultid(Integer teststepexecutionresultid) {
		this.teststepexecutionresultid = teststepexecutionresultid;
	}
  
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tescaseexecutionresultid") 
	public TestCaseExecutionResult getTestCaseExecutionResult() {
		return testCaseExecutionResult;
	}

	public void setTestCaseExecutionResult(
			TestCaseExecutionResult testCaseExecutionResult) {
		this.testCaseExecutionResult = testCaseExecutionResult;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teststepid") 
	public TestCaseStepsList getTestSteps() {
		return testSteps;
	}

	public void setTestSteps(TestCaseStepsList testSteps) {
		this.testSteps = testSteps;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testcaseid") 
	public TestCaseList getTestcase() {
		return testcase;
	}

	public void setTestcase(TestCaseList testcase) {
		this.testcase = testcase;
	}

	@Column(name = "comments", length = 2000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "result", length = 1000)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	
	@Column(name = "isApproved")
	public Integer getIsApproved() {
		return isApproved;
	}

	public void setIsApproved(Integer isApproved) {
		this.isApproved = isApproved;
	}
	@Column(name = "isReviewed")
	public Integer getIsReviewed() {
		return isReviewed;
	}

	public void setIsReviewed(Integer isReviewed) {
		this.isReviewed = isReviewed;
	}
	@Column(name = "observedOutput")
	public String getObservedOutput() {
		return observedOutput;
	}

	public void setObservedOutput(String observedOutput) {
		this.observedOutput = observedOutput;
	}
	
	@Column(name = "testStepStarttime")
	public Date getTestStepStarttime() {
		return testStepStarttime;
	}
	public void setTestStepStarttime(Date testStepStarttime) {
		this.testStepStarttime = testStepStarttime;
	}
	@Column(name = "testStepEndtime")
	public Date getTestStepEndtime() {
		return testStepEndtime;
	}
	public void setTestStepEndtime(Date testStepEndtime) {
		this.testStepEndtime = testStepEndtime;
	}
	
	@Column(name = "failureReason")
	public String getFailureReason() {
		return failureReason;
	}
	public void setFailureReason(String failureReason) {
		this.failureReason = failureReason;
	}
	public String getTestStepExpectedOutput() {
		return testStepExpectedOutput;
	}
	public void setTestStepExpectedOutput(String testStepExpectedOutput) {
		this.testStepExpectedOutput = testStepExpectedOutput;
	}
	public String getTestStepInput() {
		return testStepInput;
	}
	public void setTestStepInput(String testStepInput) {
		this.testStepInput = testStepInput;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "environmentCombinationId")
	public EnvironmentCombination getEnvironmentCombination() {
		return environmentCombination;
	}

	public void setEnvironmentCombination(
			EnvironmentCombination environmentCombination) {
		this.environmentCombination = environmentCombination;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testjobid")
	public TestRunJob getTestJob() {
		return testJob;
	}

	public void setTestJob(TestRunJob testJob) {
		this.testJob = testJob;
	}
	
	@Column(name = "evidencePath")
	public String getEvidencePath() {
		return evidencePath;
	}
	public void setEvidencePath(String evidencePath) {
		this.evidencePath = evidencePath;
	}
}
