package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestEnviromentMaster generated by hbm2java
 */
@Entity
@Table(name = "test_enviroment_master")
public class TestEnviromentMaster implements java.io.Serializable {

	private Integer testEnvironmentId;
	private DevicePlatformMaster devicePlatformMaster;
	private TestToolMaster testToolMaster;
	private Set<TestRunConfigurationChild> testRunConfigurationChilds = new HashSet<TestRunConfigurationChild>(
			0);

	public TestEnviromentMaster() {
	}

	public TestEnviromentMaster(DevicePlatformMaster devicePlatformMaster,
			TestToolMaster testToolMaster) {
		this.devicePlatformMaster = devicePlatformMaster;
		this.testToolMaster = testToolMaster;
	}

	public TestEnviromentMaster(DevicePlatformMaster devicePlatformMaster,
			TestToolMaster testToolMaster,
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.devicePlatformMaster = devicePlatformMaster;
		this.testToolMaster = testToolMaster;
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "testEnvironmentId", unique = true, nullable = false)
	public Integer getTestEnvironmentId() {
		return this.testEnvironmentId;
	}

	public void setTestEnvironmentId(Integer testEnvironmentId) {
		this.testEnvironmentId = testEnvironmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "devicePlatformName", nullable = false)
	public DevicePlatformMaster getDevicePlatformMaster() {
		return this.devicePlatformMaster;
	}

	public void setDevicePlatformMaster(
			DevicePlatformMaster devicePlatformMaster) {
		this.devicePlatformMaster = devicePlatformMaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testToolName", nullable = false)
	public TestToolMaster getTestToolMaster() {
		return this.testToolMaster;
	}

	public void setTestToolMaster(TestToolMaster testToolMaster) {
		this.testToolMaster = testToolMaster;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testEnviromentMaster")
	public Set<TestRunConfigurationChild> getTestRunConfigurationChilds() {
		return this.testRunConfigurationChilds;
	}

	public void setTestRunConfigurationChilds(
			Set<TestRunConfigurationChild> testRunConfigurationChilds) {
		this.testRunConfigurationChilds = testRunConfigurationChilds;
	}

}
