package com.hcl.atf.taf.model;

// Generated Nov 14, 2014 3:21:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestCaseList generated by hbm2java
 */
@Entity
@Table(name = "trcc_execution_plan_details")
public class TrccExecutionPlanDetails implements java.io.Serializable {

	private Integer trccExecutionPlanDetailsId;
	private TrccExecutionPlan trccExecutionPlan;
	private DeviceList deviceList;
	private TestCaseList testCaseList;
	private Integer executionOrder;
	private Integer status;
	private Date statusChangeDate;
	
	public TrccExecutionPlanDetails() {
	}

	public TrccExecutionPlanDetails(Integer trccExecutionPlanDetailsId) {
		this.trccExecutionPlanDetailsId = trccExecutionPlanDetailsId;
	}
	
	public TrccExecutionPlanDetails(TrccExecutionPlan trccExecutionPlan,
			DeviceList deviceList, TestCaseList testCaseList) {
		this.trccExecutionPlan = trccExecutionPlan;
		this.deviceList = deviceList;
		this.testCaseList = testCaseList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "trccExecutionPlanDetailsId", unique = true, nullable = false)
	public Integer getTrccExecutionPlanDetailsId() {
		return this.trccExecutionPlanDetailsId;
	}

	public void setTrccExecutionPlanDetailsId(Integer trccExecutionPlanDetailsId) {
		this.trccExecutionPlanDetailsId = trccExecutionPlanDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trccExecutionPlanId")
	public TrccExecutionPlan getTrccExecutionPlan() {
		return this.trccExecutionPlan;
	}

	public void setTrccExecutionPlan(TrccExecutionPlan trccExecutionPlan) {
		this.trccExecutionPlan = trccExecutionPlan;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deviceListId")
	public DeviceList getDeviceList() {
		return this.deviceList;
	}

	public void setDeviceList(DeviceList deviceList) {
		this.deviceList = deviceList;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testCaseId")
	public TestCaseList getTestCaseList() {
		return this.testCaseList;
	}

	public void setTestCaseList(TestCaseList testCaseList) {
		this.testCaseList = testCaseList;
	}

	@Column(name = "executionOrder")
	public Integer getExecutionOrder() {
		return this.executionOrder;
	}

	public void setExecutionOrder(Integer executionOrder) {
		this.executionOrder = executionOrder;
	}
	
	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusChangeDate")
	public Date getStatusChangeDate() {
		return statusChangeDate;
	}

	public void setStatusChangeDate(Date statusChangeDate) {
		this.statusChangeDate = statusChangeDate;
	}	
}
