package com.hcl.atf.taf.model;

// Generated Nov 14, 2014 3:21:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TestCaseList generated by hbm2java
 */
@Entity
@Table(name = "trcc_execution_plan", uniqueConstraints = @UniqueConstraint(columnNames = "trccExecutionPlanId"))
public class TrccExecutionPlan implements java.io.Serializable {

	private Integer trccExecutionPlanId;
	private String planName;
	private String description;
	private Date createdDate;
	private Date lastModifiedDate;
	private Integer status;
	private Date statusChangeDate;
	private TestRunConfigurationChild testRunConfigurationChild;

	private String isDefaultPlan;
	
	public TrccExecutionPlan() {
	}
	
	public TrccExecutionPlan(Integer trccExecutionPlanId) {
		this.trccExecutionPlanId = trccExecutionPlanId;
	}
	
	public TrccExecutionPlan(TestRunConfigurationChild testRunConfigurationChild,
			String planName, String description) {
		this.testRunConfigurationChild = testRunConfigurationChild;
		this.planName = planName;
		this.description = description;
	}
	
	public TrccExecutionPlan(TestRunConfigurationChild testRunConfigurationChild, 
			String planName, String description,
			Date createdDate,Date lastModifiedDate,Integer status, Date statusChangeDate) {
		this.testRunConfigurationChild = testRunConfigurationChild;
		this.planName = planName;
		this.description = description;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.status = status;
		this.statusChangeDate = statusChangeDate;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "trccExecutionPlanId", unique = true, nullable = false)
	public Integer getTrccExecutionPlanId() {
		return this.trccExecutionPlanId;
	}

	public void setTrccExecutionPlanId(Integer trccExecutionPlanId) {
		this.trccExecutionPlanId = trccExecutionPlanId;
	}
	
	@Column(name = "planName")
	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastModifiedDate")
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "statusChangeDate")
	public Date getStatusChangeDate() {
		return statusChangeDate;
	}

	public void setStatusChangeDate(Date statusChangeDate) {
		this.statusChangeDate = statusChangeDate;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "testRunConfigurationChildId")
	public TestRunConfigurationChild getTestRunConfigurationChild() {
		return this.testRunConfigurationChild;
	}

	public void setTestRunConfigurationChild(TestRunConfigurationChild testRunConfigurationChild) {
		this.testRunConfigurationChild = testRunConfigurationChild;
	}

	@Column(name = "isDefaultPlan")
	public String getIsDefaultPlan() {
		return this.isDefaultPlan;
	}

	public void setIsDefaultPlan(String isDefaultPlan) {
		this.isDefaultPlan = isDefaultPlan;
	}
}