package com.hcl.atf.taf.model;

// Generated Feb 11, 2015 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "user_type_master_new")
public class UserTypeMasterNew implements java.io.Serializable {

	private Integer userTypeId;
	private String userTypeName;
	private String userTypeLabel;
	private String userTypeDescription;
	private Set<UserList> userList = new HashSet<UserList>(0);

	public UserTypeMasterNew() {
	}

	public UserTypeMasterNew(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	public UserTypeMasterNew(String userTypeName, String userTypeDescription,
			Set<UserList> userList) {
		this.userTypeName = userTypeName;
		this.userTypeDescription = userTypeDescription;
		this.userList = userList;
	}


	@Column(name = "userTypeDescription", length = 50)
	public String getUserTypeDescription() {
		return this.userTypeDescription;
	}

	public void setUserTypeDescription(String userTypeDescription) {
		this.userTypeDescription = userTypeDescription;
	}

	@Id
	@Column(name = "userTypeId", unique = true, nullable = false, length = 20)
	public Integer getUserTypeId() {
		return userTypeId;
	}

	public void setUserTypeId(Integer userTypeId) {
		this.userTypeId = userTypeId;
	}

	@Column(name = "userTypeName", length = 50)
	public String getUserTypeName() {
		return userTypeName;
	}

	public void setUserTypeName(String userTypeName) {
		this.userTypeName = userTypeName;
	}

	@Column(name = "userTypeLabel", length = 50)
	public String getUserTypeLabel() {
		return userTypeLabel;
	}

	public void setUserTypeLabel(String userTypeLabel) {
		this.userTypeLabel = userTypeLabel;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTypeMasterNew")
	public Set<UserList> getUserList() {
		return this.userList;
	}
	
	public void setUserList(Set<UserList> userList) {
		this.userList = userList;
	}

}
