package com.hcl.atf.taf.model;

// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTypeMaster generated by hbm2java
 */
@Entity
@Table(name = "user_type_master")
public class UserTypeMaster implements java.io.Serializable {

	private String userType;
	private String userTypeDescription;
	private Set<UserList> userLists = new HashSet<UserList>(0);

	public UserTypeMaster() {
	}

	public UserTypeMaster(String userType) {
		this.userType = userType;
	}

	public UserTypeMaster(String userType, String userTypeDescription,
			Set<UserList> userLists) {
		this.userType = userType;
		this.userTypeDescription = userTypeDescription;
		this.userLists = userLists;
	}

	@Id
	@Column(name = "userType", unique = true, nullable = false, length = 20)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "userTypeDescription", length = 50)
	public String getUserTypeDescription() {
		return this.userTypeDescription;
	}

	public void setUserTypeDescription(String userTypeDescription) {
		this.userTypeDescription = userTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTypeMasterNew")
	public Set<UserList> getUserLists() {
		return this.userLists;
	}

	public void setUserLists(Set<UserList> userLists) {
		this.userLists = userLists;
	}

}
