package com.hcl.atf.taf.model;


// Generated Feb 4, 2014 4:30:16 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductMaster generated by hbm2java
 */
@Entity
@Table(name = "user_role_master")
public class UserRoleMaster implements java.io.Serializable {

	private Integer userRoleId;
	private String roleName;
	private String roleLabel;
	private String description;
	
	private Integer status;
	
	public UserRoleMaster() {
	}

	public UserRoleMaster(String roleName, String roleLable,String description,Integer status) {
		this.roleName=roleName;
		this.roleLabel=roleLabel;
		this.description=description;
		this.status=status;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userRoleId", unique = true)
	public Integer getUserRoleId() {
		return userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	@Column(name = "roleName", nullable = false, length = 100)
	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "roleLabel", nullable = false, length = 100)
	public String getRoleLabel() {
		return roleLabel;
	}

	public void setRoleLabel(String roleLabel) {
		this.roleLabel = roleLabel;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	

}
